# Generated by Django 4.1 on 2022-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor_med_org_patient_med_org_alter_doctor_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('педиатор', 'педиатор'), ('терапевт ', 'терапевт'), ('офтальмолог', 'офтальмолог'), ('стоматолог', 'стоматолог'), ('акушер-гинеколог', 'акушер-гинеколог'), ('специалист', 'специалист')], default='----', max_length=50, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Болька 1'), ('2', 'Болька 2'), ('3', 'Болька 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Павловский', 'Павловский район'), ('Мелекесский', 'Мелекесский район'), ('Инзенский', 'Инзенский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новоспасский', 'Новоспасский район'), ('Ульяновский', 'Ульяновский район'), ('', '----'), ('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Майнский', 'Майнский район'), ('Барышский', 'Барышский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('2-', 'A(II) Rh- '), ('3-', 'B(III) Rh- '), ('3+', 'B(III) Rh+ '), ('1+', 'O(I) Rh+ '), ('4+', 'AB(IV) Rh+'), ('2+', 'A(II) Rh+ '), ('1-', 'O(I) Rh- '), ('4-', 'AB(IV) Rh-')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('', '----'), ('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('', '----'), ('f', 'Женщина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('6', 'ООО «КАПИТАЛ МС» ')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Болька 1'), ('2', 'Болька 2'), ('3', 'Болька 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('h', 'Высший'), ('l', 'Низший'), ('m', 'Средний')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Павловский', 'Павловский район'), ('Мелекесский', 'Мелекесский район'), ('Инзенский', 'Инзенский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новоспасский', 'Новоспасский район'), ('Ульяновский', 'Ульяновский район'), ('', '----'), ('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Майнский', 'Майнский район'), ('Барышский', 'Барышский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
