# Generated by Django 4.0.2 on 2022-10-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctor_role_alter_doctor_med_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionnotes',
            name='med_organization',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Болька 1'), ('2', 'Болька 2'), ('3', 'Болька 3')], max_length=10, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('специалист', 'специалист'), ('терапевт ', 'терапевт'), ('стоматолог', 'стоматолог'), ('педиатор', 'педиатор'), ('акушер-гинеколог', 'акушер-гинеколог'), ('офтальмолог', 'офтальмолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Карсунский', 'Карсунский район'), ('Новоспасский', 'Новоспасский район'), ('Сурский', 'Сурский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Барышский', 'Барышский район'), ('Инзенский', 'Инзенский район'), ('', '----'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район'), ('Ульяновский', 'Ульяновский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Радищевский', 'Радищевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Павловский', 'Павловский район'), ('Базарносызганский', 'Базарносызганский район'), ('Кузоватовский', 'Кузоватовский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('2-', 'A(II) Rh- '), ('1-', 'O(I) Rh- '), ('2+', 'A(II) Rh+ '), ('1+', 'O(I) Rh+ '), ('3+', 'B(III) Rh+ '), ('4-', 'AB(IV) Rh-'), ('3-', 'B(III) Rh- '), ('4+', 'AB(IV) Rh+')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('', '----'), ('1', 'Город'), ('2', 'Село')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('3', 'Третья'), ('1', 'Первая'), ('2', 'Вторая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', '----'), ('m', 'Мужчина'), ('f', 'Женщина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Карсунский', 'Карсунский район'), ('Новоспасский', 'Новоспасский район'), ('Сурский', 'Сурский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Барышский', 'Барышский район'), ('Инзенский', 'Инзенский район'), ('', '----'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район'), ('Ульяновский', 'Ульяновский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Радищевский', 'Радищевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Павловский', 'Павловский район'), ('Базарносызганский', 'Базарносызганский район'), ('Кузоватовский', 'Кузоватовский район')], max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
    ]
