# Generated by Django 4.0.2 on 2022-10-04 18:40

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='medicalcard',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicalcard',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('терапевт ', 'терапевт'), ('стоматолог', 'стоматолог'), ('акушер-гинеколог', 'акушер-гинеколог'), ('педиатор', 'педиатор'), ('офтальмолог', 'офтальмолог'), ('специалист', 'специалист')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Новомалыклинский', 'Новомалыклинский район'), ('Майнский', 'Майнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Новоспасский', 'Новоспасский район'), ('Старомайнский', 'Старомайнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Павловский', 'Павловский район'), ('Сурский', 'Сурский район'), ('Мелекесский', 'Мелекесский район'), ('Карсунский', 'Карсунский район'), ('', '----'), ('Барышский', 'Барышский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Полных лет'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='allergy_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание аллергической реакции'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='childbirth_gestation_period',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Срок беременности родов (недели)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-12', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='first_visit_date',
            field=models.DateField(blank=True, verbose_name='Дата первой явки (взятие на учет)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='gestation_period_weeks',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Срок беременности (недели)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('3', 'Состоит в незарегистриро-ванном браке'), ('5', 'Разведена'), ('', '----'), ('2', 'Состоит в зарегистри-рованном браке'), ('6', 'Разошлась'), ('4', 'Вдова'), ('1', 'Никогда не состояла в браке')], default='', max_length=1, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, region=None, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='oms_policy',
            field=models.CharField(blank=True, max_length=16, verbose_name='Полис ОМС'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='registration_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес регистрции'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='residence_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='snils',
            field=models.CharField(blank=True, max_length=11, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='trusted_person_fio',
            field=models.CharField(blank=True, max_length=300, verbose_name='ФИО доверенного лица'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='trusted_person_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, region=None, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('1+', 'O(I) Rh+ '), ('2-', 'A(II) Rh- '), ('3-', 'B(III) Rh- '), ('1-', 'O(I) Rh- '), ('2+', 'A(II) Rh+ '), ('4-', 'AB(IV) Rh-'), ('4+', 'AB(IV) Rh+'), ('3+', 'B(III) Rh+ ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('1', 'Город'), ('', '----'), ('2', 'Село')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('3', 'Третья'), ('2', 'Вторая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Новомалыклинский', 'Новомалыклинский район'), ('Майнский', 'Майнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Новоспасский', 'Новоспасский район'), ('Старомайнский', 'Старомайнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Павловский', 'Павловский район'), ('Сурский', 'Сурский район'), ('Мелекесский', 'Мелекесский район'), ('Карсунский', 'Карсунский район'), ('', '----'), ('Барышский', 'Барышский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
