# Generated by Django 4.0.2 on 2022-10-06 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_medicalcard_options_remove_medicalcard_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicalcard',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Полных лет'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='father_date_of_determination',
            field=models.DateField(blank=True, default='2022-01-01', null=True, verbose_name='Дата определения'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='mother_date_of_determination',
            field=models.DateField(blank=True, default='2022-01-01', null=True, verbose_name='Дата определения'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('педиатор', 'педиатор'), ('специалист', 'специалист'), ('терапевт ', 'терапевт'), ('акушер-гинеколог', 'акушер-гинеколог'), ('стоматолог', 'стоматолог'), ('офтальмолог', 'офтальмолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Сурский', 'Сурский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Цильнинский', 'Цильнинский район'), ('Карсунский', 'Карсунский район'), ('Чердаклинский', 'Чердаклинский район '), ('Старомайнский', 'Старомайнский район'), ('Радищевский', 'Радищевский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Новоспасский', 'Новоспасский район'), ('Инзенский', 'Инзенский район'), ('Николаевский', 'Николаевский район'), ('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Ульяновский', 'Ульяновский район'), ('', '----'), ('Павловский', 'Павловский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Тереньгульский', 'Тереньгульский район'), ('Старокулаткинский', 'Старокулаткинский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('3', 'Состоит в незарегистрированном браке'), ('5', 'Разведена'), ('4', 'Вдова'), ('2', 'Состоит в зарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('', '----'), ('6', 'Разошлась')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Женский'), ('m', 'Мужской'), ('', '----')], default='f', max_length=1, verbose_name='Пол'),
        ),
    ]
