# Generated by Django 4.0.2 on 2022-10-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_medicalcard_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='births_by_term',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Данные роды по сроку'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('специалист', 'специалист'), ('акушер-гинеколог', 'акушер-гинеколог'), ('терапевт ', 'терапевт'), ('стоматолог', 'стоматолог'), ('педиатор', 'педиатор'), ('офтальмолог', 'офтальмолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Инзенский', 'Инзенский район'), ('Тереньгульский', 'Тереньгульский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('Радищевский', 'Радищевский район'), ('Мелекесский', 'Мелекесский район'), ('', '----'), ('Сенгилеевский', 'Сенгилеевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Базарносызганский', 'Базарносызганский район'), ('Павловский', 'Павловский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Вешкаймский', 'Вешкаймский район'), ('Николаевский', 'Николаевский район'), ('Цильнинский', 'Цильнинский район'), ('Сурский', 'Сурский район'), ('Ульяновский', 'Ульяновский район'), ('Карсунский', 'Карсунский район'), ('Старомайнский', 'Старомайнский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('3', 'B(III)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('2', 'Состоит в зарегистрированном браке'), ('5', 'Разведена'), ('', '----'), ('1', 'Никогда не состояла в браке'), ('6', 'Разошлась'), ('4', 'Вдова'), ('3', 'Состоит в незарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('3', 'B(III)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.CreateModel(
            name='ObstetricRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(blank=True, choices=[('1', 'Первая явка'), ('18-20', 'Явка на 18-20 неделе'), ('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='home.medicalcard')),
            ],
            options={
                'verbose_name': 'Акушерский риск',
                'verbose_name_plural': 'Акушерские риски',
            },
        ),
        migrations.CreateModel(
            name='ComplicationRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complication_risk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Риск осложнениний')),
                ('risk_value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Значение индивидуального риска')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comlications', to='home.obstetricrisk')),
            ],
            options={
                'verbose_name': 'Риск осложнения',
                'verbose_name_plural': 'Риски осложнений',
            },
        ),
    ]
