# Generated by Django 4.1 on 2022-10-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRecomendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название документа')),
                ('document', models.FileField(upload_to='uploads/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Клиническая рекомендация',
                'verbose_name_plural': 'Клинические рекомендации',
            },
        ),
    ]
