version: '3.3'

services:
 med_system:
   build:
     context: .
   volumes:
     - static:/static
   env_file:
     - .env.dev
   ports:
     - "8000:8000"

 nginx:
   build: ./nginx
   volumes:
   - static:/static
   ports:
     - "80:80"
   depends_on:
     - med_system

volumes:
 static: