version: '3.9'

services:

  med_system:
    build: .
    command: python /usr/src/akineo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/akineo
    ports:
      - 8000:8000
    depends_on:
      - med_system_db

  med_system_db:
  image: postgres:15-alpine
  volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: