from django.contrib import admin
from .models import *

admin.site.register(Patient)
admin.site.register(Doctor)
admin.site.register(SelfMonitoringRecords)
admin.site.register(File)
admin.site.register(ReceptionNotes)
admin.site.register(MedicalCard)
admin.site.register(PregnancyOutcome)
admin.site.register(ObstetricRisk)
admin.site.register(ComplicationRisk)

# observation
admin.site.register(CurrentPregnancy)
admin.site.register(Pelviometry)
admin.site.register(PregnantWomanMonitoring)
admin.site.register(AppointmentList)
admin.site.register(TakingMedications)
admin.site.register(AntibodiesDetermination)
admin.site.register(RubellaVirus)
admin.site.register(AntiresusBodies)
admin.site.register(BloodAnalysis)
admin.site.register(BiochemicalBloodAnalysis)
admin.site.register(Coagulogram)
admin.site.register(GlucoseToleranceTest)
admin.site.register(ThyroidStimulatingHormone)
admin.site.register(Smears)
admin.site.register(BacterioscopicSmearsExamination)
admin.site.register(CervixCytologicalExamination)
admin.site.register(UrineAnalysis)
admin.site.register(UrineSowing)

admin.site.register(PatientInformation)
admin.site.register(CarvixScar)
admin.site.register(FatherInfo)

admin.site.register(DoctorExaminationsTherapist)
admin.site.register(DoctorExaminationsDentist)
admin.site.register(DoctorExaminationsPediator)
admin.site.register(DoctorExaminationsSpecialist)
admin.site.register(DoctorExaminationsOphthalmologist)
admin.site.register(DoctorExaminationsObstetricianGynecologist)

admin.site.register(CurrentPregnancyinfo)
admin.site.register(FirstExamination)
admin.site.register(UltrasoundFisrtTrimester)
admin.site.register(ComprehensiveRiskAssessment)
admin.site.register(UltrasoundExamination_19_21)
admin.site.register(UltrasoundExamination_30_34)
admin.site.register(MODelivery)

admin.site.register(SAMD)
admin.site.register(TelegramUsers)
admin.site.register(Notifications)
