# Generated by Django 4.1 on 2022-09-01 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default='2000-01-12', verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='f', max_length=1, verbose_name='Пол')),
                ('social_status', models.CharField(blank=True, choices=[('l', 'Низший'), ('h', 'Высший'), ('m', 'Средний')], max_length=1, verbose_name='Соц. Статус')),
                ('disability', models.CharField(blank=True, choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья')], max_length=1, verbose_name='Инвалидность')),
                ('blood', models.CharField(blank=True, choices=[('1+', 'O(I) Rh+ '), ('3+', 'B(III) Rh+ '), ('1-', 'O(I) Rh- '), ('4-', 'AB(IV) Rh-'), ('4+', 'AB(IV) Rh+'), ('2+', 'A(II) Rh+ '), ('2-', 'A(II) Rh- '), ('3-', 'B(III) Rh- ')], max_length=2, verbose_name='Группа крови')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефонный номер')),
                ('work_address', models.CharField(blank=True, max_length=150, verbose_name='Адресс работы')),
                ('oms_policy', models.CharField(blank=True, max_length=16, verbose_name='Полис ОМС')),
                ('insurance', models.CharField(blank=True, choices=[('6', 'ООО «КАПИТАЛ МС» '), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)')], max_length=1, verbose_name='Сраховая компания')),
                ('snils', models.CharField(blank=True, max_length=11, verbose_name='СНИЛС')),
                ('city_village', models.CharField(choices=[('1', 'Город'), ('2', 'Село')], max_length=1, verbose_name='Житель города/села')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адресс')),
                ('territory', models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Ульяновский', 'Ульяновский район'), ('Сурский', 'Сурский район'), ('Базарносызганский', 'Базарносызганский район'), ('Инзенский', 'Инзенский район'), ('Карсунский', 'Карсунский район'), ('Чердаклинский', 'Чердаклинский район '), ('Старомайнский', 'Старомайнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Радищевский', 'Радищевский район'), ('Цильнинский', 'Цильнинский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Майнский', 'Майнский район'), ('Новоспасский', 'Новоспасский район'), ('Павловский', 'Павловский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Барышский', 'Барышский район'), ('Мелекесский', 'Мелекесский район')], max_length=25, verbose_name='Территория')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(max_length=6, verbose_name='Кабинет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
