# Generated by Django 4.1 on 2022-09-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_changed', models.CharField(default='', max_length=100, verbose_name='Кто изменил')),
                ('modified_model', models.CharField(default='', max_length=100, verbose_name='Кого изменили')),
                ('change_type', models.CharField(max_length=100, verbose_name='Изменение')),
                ('before', models.CharField(default='', max_length=500, verbose_name='Было')),
                ('after', models.CharField(default='', max_length=500, verbose_name='Стало')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='usr', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='sur', max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('cabinet', models.CharField(max_length=6, verbose_name='Кабинет')),
                ('territory', models.CharField(choices=[('Вешкаймский', 'Вешкаймский район'), ('Инзенский', 'Инзенский район'), ('Барышский', 'Барышский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Радищевский', 'Радищевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Майнский', 'Майнский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Мелекесский', 'Мелекесский район'), ('Ульяновский', 'Ульяновский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новомалыклинский', 'Новомалыклинский район'), ('Старомайнский', 'Старомайнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('Николаевский', 'Николаевский район')], default='Ульяновский', max_length=25, verbose_name='Территория')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(default='2000-01-12', verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], default='f', max_length=1, verbose_name='Пол')),
                ('social_status', models.CharField(blank=True, choices=[('l', 'Низший'), ('h', 'Высший'), ('m', 'Средний')], max_length=1, verbose_name='Соц. Статус')),
                ('disability', models.CharField(blank=True, choices=[('3', 'Третья'), ('1', 'Первая'), ('2', 'Вторая')], max_length=1, verbose_name='Инвалидность')),
                ('blood', models.CharField(blank=True, choices=[('3-', 'B(III) Rh- '), ('3+', 'B(III) Rh+ '), ('1-', 'O(I) Rh- '), ('2-', 'A(II) Rh- '), ('4-', 'AB(IV) Rh-'), ('4+', 'AB(IV) Rh+'), ('2+', 'A(II) Rh+ '), ('1+', 'O(I) Rh+ ')], max_length=2, verbose_name='Группа крови')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефонный номер')),
                ('work_address', models.CharField(blank=True, max_length=150, verbose_name='Адресс работы')),
                ('oms_policy', models.CharField(blank=True, max_length=16, verbose_name='Полис ОМС')),
                ('insurance', models.CharField(blank=True, choices=[('6', 'ООО «КАПИТАЛ МС» '), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('2', 'ООО «МСК «МЕДСТРАХ»»')], max_length=1, verbose_name='Сраховая компания')),
                ('snils', models.CharField(blank=True, max_length=11, verbose_name='СНИЛС')),
                ('city_village', models.CharField(choices=[('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адресс')),
                ('territory', models.CharField(choices=[('Вешкаймский', 'Вешкаймский район'), ('Инзенский', 'Инзенский район'), ('Барышский', 'Барышский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Радищевский', 'Радищевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Майнский', 'Майнский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Мелекесский', 'Мелекесский район'), ('Ульяновский', 'Ульяновский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новомалыклинский', 'Новомалыклинский район'), ('Старомайнский', 'Старомайнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('Николаевский', 'Николаевский район')], max_length=25, verbose_name='Территория')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_death', models.DateTimeField(blank=True, null=True, verbose_name='Дата смерти')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='SelfMonitoringRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting', models.DateTimeField(verbose_name='Время приема')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
            options={
                'verbose_name': 'Запись приема',
                'verbose_name_plural': 'Записи приема',
                'ordering': ['-date_meeting', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=270, verbose_name='Заболевание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_cured', models.DateTimeField(blank=True, null=True, verbose_name='Дата излечения')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='home.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='home.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
