# Generated by Django 4.0.2 on 2022-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('педиатор', 'педиатор'), ('офтальмолог', 'офтальмолог'), ('терапевт ', 'терапевт'), ('акушер-гинеколог', 'акушер-гинеколог'), ('стоматолог', 'стоматолог'), ('специалист', 'специалист')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Майнский', 'Майнский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Карсунский', 'Карсунский район'), ('Николаевский', 'Николаевский район'), ('Чердаклинский', 'Чердаклинский район '), ('Барышский', 'Барышский район'), ('Тереньгульский', 'Тереньгульский район'), ('Ульяновский', 'Ульяновский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Старомайнский', 'Старомайнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Мелекесский', 'Мелекесский район'), ('', '----'), ('Радищевский', 'Радищевский район'), ('Вешкаймский', 'Вешкаймский район'), ('Инзенский', 'Инзенский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Павловский', 'Павловский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('1', 'Никогда не состояла в браке'), ('6', 'Разошлась'), ('5', 'Разведена'), ('4', 'Вдова'), ('3', 'Состоит в незарегистрированном браке'), ('', '----'), ('2', 'Состоит в зарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('11-14', 'Явка на 11-14 неделе'), ('1', 'Первая явка'), ('18-20', 'Явка на 18-20 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Женский'), ('', '----'), ('m', 'Мужской')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('b', 'Роды'), ('d', 'Смерть'), ('a', 'Аборт')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('под', 'Подвижна'), ('приж', 'Прижата')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('попер', 'Попереченое'), ('кос', 'Косое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
    ]
