# Generated by Django 4.0.2 on 2022-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='med_org',
            field=models.CharField(blank=True, choices=[('1', 'Болька 1'), ('2', 'Болька 2'), ('3', 'Болька 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_org',
            field=models.CharField(blank=True, choices=[('1', 'Болька 1'), ('2', 'Болька 2'), ('3', 'Болька 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='home.Patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Павловский', 'Павловский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Чердаклинский', 'Чердаклинский район '), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Николаевский', 'Николаевский район'), ('Новоспасский', 'Новоспасский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Барышский', 'Барышский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Радищевский', 'Радищевский район'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('1-', 'O(I) Rh- '), ('2+', 'A(II) Rh+ '), ('3+', 'B(III) Rh+ '), ('4-', 'AB(IV) Rh-'), ('2-', 'A(II) Rh- '), ('3-', 'B(III) Rh- '), ('4+', 'AB(IV) Rh+'), ('1+', 'O(I) Rh+ ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('1', 'Город'), ('2', 'Село')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('2', 'Вторая'), ('3', 'Третья'), ('1', 'Первая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('2', 'ООО «МСК «МЕДСТРАХ»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('m', 'Средний'), ('h', 'Высший'), ('l', 'Низший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Павловский', 'Павловский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Кузоватовский', 'Кузоватовский район'), ('Чердаклинский', 'Чердаклинский район '), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Николаевский', 'Николаевский район'), ('Новоспасский', 'Новоспасский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Барышский', 'Барышский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Радищевский', 'Радищевский район'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
