# Generated by Django 4.1 on 2022-08-30 16:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood',
            field=models.CharField(blank=True, choices=[('3+', 'B(III) Rh+ '), ('1+', 'O(I) Rh+ '), ('1-', 'O(I) Rh- '), ('4+', 'AB(IV) Rh+'), ('2-', 'A(II) Rh- '), ('2+', 'A(II) Rh+ '), ('3-', 'B(III) Rh- '), ('4-', 'AB(IV) Rh-')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city_village',
            field=models.CharField(choices=[('2', 'Села'), ('1', 'Города')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='insurance',
            field=models.CharField(blank=True, choices=[('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('6', 'ООО «КАПИТАЛ МС» '), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='oms_policy',
            field=models.CharField(blank=True, max_length=16, verbose_name='Полис ОМС'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='snils',
            field=models.CharField(blank=True, max_length=11, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_status',
            field=models.CharField(blank=True, choices=[('m', 'Средний'), ('l', 'Низший'), ('h', 'Высший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='territory',
            field=models.CharField(choices=[('Павловский', 'Павловский район'), ('Радищевский', 'Радищевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Инзенский', 'Инзенский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Сурский', 'Сурский район'), ('Вешкаймский', 'Вешкаймский район'), ('Мелекесский', 'Мелекесский район'), ('Карсунский', 'Карсунский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Базарносызганский', 'Базарносызганский район'), ('Кузоватовский', 'Кузоватовский район'), ('Николаевский', 'Николаевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Ульяновский', 'Ульяновский район'), ('Цильнинский', 'Цильнинский район'), ('Старомайнский', 'Старомайнский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
