# Generated by Django 4.1 on 2022-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='usr', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='sur', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cabinet',
            field=models.CharField(default='301', max_length=6, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('4-', 'AB(IV) Rh-'), ('3-', 'B(III) Rh- '), ('2-', 'A(II) Rh- '), ('1-', 'O(I) Rh- '), ('1+', 'O(I) Rh+ '), ('2+', 'A(II) Rh+ '), ('3+', 'B(III) Rh+ '), ('4+', 'AB(IV) Rh+')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('5', 'ООО «Страховая компания «Ингосстрах-М»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('m', 'Средний'), ('l', 'Низший'), ('h', 'Высший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Мелекесский', 'Мелекесский район'), ('Тереньгульский', 'Тереньгульский район'), ('Николаевский', 'Николаевский район'), ('Радищевский', 'Радищевский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новоспасский', 'Новоспасский район'), ('Барышский', 'Барышский район'), ('Ульяновский', 'Ульяновский район'), ('Старомайнский', 'Старомайнский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Вешкаймский', 'Вешкаймский район'), ('Майнский', 'Майнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Павловский', 'Павловский район'), ('Карсунский', 'Карсунский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
