# Generated by Django 4.0.2 on 2022-09-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('3-', 'B(III) Rh- '), ('2-', 'A(II) Rh- '), ('3+', 'B(III) Rh+ '), ('2+', 'A(II) Rh+ '), ('1-', 'O(I) Rh- '), ('1+', 'O(I) Rh+ '), ('4+', 'AB(IV) Rh+'), ('4-', 'AB(IV) Rh-')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('2', 'Вторая'), ('1', 'Первая'), ('3', 'Третья')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Павловский', 'Павловский район'), ('Радищевский', 'Радищевский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Старомайнский', 'Старомайнский район'), ('Новоспасский', 'Новоспасский район'), ('Цильнинский', 'Цильнинский район'), ('Ульяновский', 'Ульяновский район'), ('Кузоватовский', 'Кузоватовский район'), ('Вешкаймский', 'Вешкаймский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Тереньгульский', 'Тереньгульский район'), ('Николаевский', 'Николаевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Барышский', 'Барышский район'), ('Карсунский', 'Карсунский район'), ('Базарносызганский', 'Базарносызганский район')], max_length=25, verbose_name='Территория'),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=100, verbose_name='Заболевание')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='home.patient')),
            ],
        ),
    ]
