# Generated by Django 4.0.2 on 2022-10-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('офтальмолог', 'офтальмолог'), ('педиатор', 'педиатор'), ('стоматолог', 'стоматолог'), ('специалист', 'специалист'), ('акушер-гинеколог', 'акушер-гинеколог'), ('терапевт ', 'терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Барышский', 'Барышский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Майнский', 'Майнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Тереньгульский', 'Тереньгульский район'), ('Новоспасский', 'Новоспасский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Цильнинский', 'Цильнинский район'), ('Мелекесский', 'Мелекесский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старомайнский', 'Старомайнский район'), ('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Ульяновский', 'Ульяновский район'), ('Карсунский', 'Карсунский район'), ('', '----')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('a', 'Алкоголь'), ('s', 'Курение'), ('d', 'Наркотики'), ('', '----')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('5', 'Разведена'), ('3', 'Состоит в незарегистрированном браке'), ('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('', '----')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('', '----')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц'), ('1', 'Каждый день'), ('', '----')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='another_risks',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Другие риски'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='growth_retardation_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск задержки роста плода'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('0', 'Отрицательный'), ('1', 'Положительный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='preeclampsia_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преэклампсии'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='premature_birth_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преждевременных родов'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('2', 'Умеренные'), ('3', 'Обильные'), ('1', 'Скудные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('1/2-1', 'От 1/2 до 1 пачки'), ('1>', 'Больше 1 пачки'), ('<1/2', 'Меньше 1/2 пачки'), ('', '----')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='thromboembolic_complications',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск тромбоэболических осложнений'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('a', 'Искусственный'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('swc', 'Самопроизвольным - без осложнений'), ('sc', 'Самопроизвольным - с осложнениями'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('b', 'Роды'), ('a', 'Аборт'), ('d', 'Смерть')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('прод', 'Продольное'), ('попер', 'Попереченое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('гол', 'Головка'), ('др', 'Другое'), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
    ]
