# Generated by Django 4.0.2 on 2022-09-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patient_blood_alter_patient_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='home.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('3+', 'B(III) Rh+ '), ('4-', 'AB(IV) Rh-'), ('1-', 'O(I) Rh- '), ('3-', 'B(III) Rh- '), ('1+', 'O(I) Rh+ '), ('2+', 'A(II) Rh+ '), ('4+', 'AB(IV) Rh+'), ('2-', 'A(II) Rh- ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('2', 'Вторая'), ('3', 'Третья'), ('1', 'Первая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('2', 'ООО «МСК «МЕДСТРАХ»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('6', 'ООО «КАПИТАЛ МС» '), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('h', 'Высший'), ('m', 'Средний'), ('l', 'Низший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Майнский', 'Майнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старомайнский', 'Старомайнский район'), ('Карсунский', 'Карсунский район'), ('Вешкаймский', 'Вешкаймский район'), ('Радищевский', 'Радищевский район'), ('Новоспасский', 'Новоспасский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Ульяновский', 'Ульяновский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Кузоватовский', 'Кузоватовский район'), ('Сурский', 'Сурский район'), ('Базарносызганский', 'Базарносызганский район'), ('Николаевский', 'Николаевский район'), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Барышский', 'Барышский район'), ('Цильнинский', 'Цильнинский район'), ('Старокулаткинский', 'Старокулаткинский район')], max_length=25, verbose_name='Территория'),
        ),
        migrations.CreateModel(
            name='SelfMonitoringRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='home.patient')),
            ],
        ),
    ]
