# Generated by Django 4.1 on 2022-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_patient_blood_alter_patient_city_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('4-', 'AB(IV) Rh-'), ('2+', 'A(II) Rh+ '), ('4+', 'AB(IV) Rh+'), ('1+', 'O(I) Rh+ '), ('3-', 'B(III) Rh- '), ('3+', 'B(III) Rh+ '), ('1-', 'O(I) Rh- '), ('2-', 'A(II) Rh- ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('6', 'ООО «КАПИТАЛ МС» '), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('2', 'ООО «МСК «МЕДСТРАХ»»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Майнский', 'Майнский район'), ('Сурский', 'Сурский район'), ('Радищевский', 'Радищевский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Старомайнский', 'Старомайнский район'), ('Павловский', 'Павловский район'), ('Вешкаймский', 'Вешкаймский район'), ('Барышский', 'Барышский район'), ('Кузоватовский', 'Кузоватовский район'), ('Цильнинский', 'Цильнинский район'), ('Карсунский', 'Карсунский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Ульяновский', 'Ульяновский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старокулаткинский', 'Старокулаткинский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
