# Generated by Django 4.0.2 on 2022-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_patient_blood_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Ульяновский', 'Ульяновский район'), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Барышский', 'Барышский район'), ('Старомайнский', 'Старомайнский район'), ('Карсунский', 'Карсунский район'), ('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Инзенский', 'Инзенский район'), ('Цильнинский', 'Цильнинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Кузоватовский', 'Кузоватовский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('4+', 'AB(IV) Rh+'), ('2+', 'A(II) Rh+ '), ('1-', 'O(I) Rh- '), ('1+', 'O(I) Rh+ '), ('4-', 'AB(IV) Rh-'), ('2-', 'A(II) Rh- '), ('3-', 'B(III) Rh- '), ('3+', 'B(III) Rh+ ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('2', 'Вторая'), ('3', 'Третья'), ('1', 'Первая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('2', 'ООО «МСК «МЕДСТРАХ»»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('m', 'Средний'), ('l', 'Низший'), ('h', 'Высший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Ульяновский', 'Ульяновский район'), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Барышский', 'Барышский район'), ('Старомайнский', 'Старомайнский район'), ('Карсунский', 'Карсунский район'), ('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Инзенский', 'Инзенский район'), ('Цильнинский', 'Цильнинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Кузоватовский', 'Кузоватовский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
