# Generated by Django 4.0.2 on 2022-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_changed', models.CharField(default='', max_length=100, verbose_name='Кто изменил')),
                ('modified_model', models.CharField(default='', max_length=100, verbose_name='Кого изменили')),
                ('before', models.CharField(default='', max_length=500, verbose_name='Было')),
                ('after', models.CharField(default='', max_length=500, verbose_name='Стало')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Инзенский', 'Инзенский район'), ('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Новоспасский', 'Новоспасский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Вешкаймский', 'Вешкаймский район'), ('Радищевский', 'Радищевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Мелекесский', 'Мелекесский район'), ('Чердаклинский', 'Чердаклинский район '), ('Майнский', 'Майнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район'), ('Ульяновский', 'Ульяновский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Николаевский', 'Николаевский район'), ('Сурский', 'Сурский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('3-', 'B(III) Rh- '), ('1-', 'O(I) Rh- '), ('4+', 'AB(IV) Rh+'), ('1+', 'O(I) Rh+ '), ('3+', 'B(III) Rh+ '), ('2+', 'A(II) Rh+ '), ('4-', 'AB(IV) Rh-'), ('2-', 'A(II) Rh- ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('6', 'ООО «КАПИТАЛ МС» '), ('2', 'ООО «МСК «МЕДСТРАХ»»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('h', 'Высший'), ('m', 'Средний'), ('l', 'Низший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Инзенский', 'Инзенский район'), ('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Новоспасский', 'Новоспасский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Вешкаймский', 'Вешкаймский район'), ('Радищевский', 'Радищевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Мелекесский', 'Мелекесский район'), ('Чердаклинский', 'Чердаклинский район '), ('Майнский', 'Майнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район'), ('Ульяновский', 'Ульяновский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Николаевский', 'Николаевский район'), ('Сурский', 'Сурский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
