# Generated by Django 4.0.2 on 2022-10-04 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_medicalcard_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('стоматолог', 'стоматолог'), ('терапевт ', 'терапевт'), ('педиатор', 'педиатор'), ('офтальмолог', 'офтальмолог'), ('акушер-гинеколог', 'акушер-гинеколог'), ('специалист', 'специалист')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Старомайнский', 'Старомайнский район'), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Ульяновский', 'Ульяновский район'), ('Вешкаймский', 'Вешкаймский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('', '----'), ('Радищевский', 'Радищевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Сурский', 'Сурский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Полных лет'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='childbirth_gestation_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Срок беременности родов (недели)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='gestation_period_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Срок беременности (недели)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('3', 'Состоит в незарегистриро-ванном браке'), ('2', 'Состоит в зарегистри-рованном браке'), ('5', 'Разведена'), ('', '----'), ('6', 'Разошлась'), ('1', 'Никогда не состояла в браке'), ('4', 'Вдова')], default='', max_length=1, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='pregnancy_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Беременность по счету'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('1-', 'O(I) Rh- '), ('3+', 'B(III) Rh+ '), ('2-', 'A(II) Rh- '), ('2+', 'A(II) Rh+ '), ('3-', 'B(III) Rh- '), ('1+', 'O(I) Rh+ '), ('4+', 'AB(IV) Rh+'), ('4-', 'AB(IV) Rh-')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('', '----'), ('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('3', 'Третья'), ('1', 'Первая'), ('2', 'Вторая')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('2', 'ООО «МСК «МЕДСТРАХ»»'), ('6', 'ООО «КАПИТАЛ МС» '), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Старомайнский', 'Старомайнский район'), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Ульяновский', 'Ульяновский район'), ('Вешкаймский', 'Вешкаймский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('', '----'), ('Радищевский', 'Радищевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Сурский', 'Сурский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
