# Generated by Django 4.1 on 2022-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_changecontrollog_change_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date_cured',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата излечения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_death',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cabinet',
            field=models.CharField(max_length=6, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Чердаклинский', 'Чердаклинский район '), ('Базарносызганский', 'Базарносызганский район'), ('Цильнинский', 'Цильнинский район'), ('Тереньгульский', 'Тереньгульский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Барышский', 'Барышский район'), ('Николаевский', 'Николаевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район'), ('Новоспасский', 'Новоспасский район'), ('Сурский', 'Сурский район'), ('Кузоватовский', 'Кузоватовский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='disease',
            field=models.CharField(max_length=270, verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('3+', 'B(III) Rh+ '), ('4+', 'AB(IV) Rh+'), ('2-', 'A(II) Rh- '), ('1+', 'O(I) Rh+ '), ('1-', 'O(I) Rh- '), ('2+', 'A(II) Rh+ '), ('3-', 'B(III) Rh- '), ('4-', 'AB(IV) Rh-')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('2', 'Село'), ('1', 'Город')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('6', 'ООО «КАПИТАЛ МС» '), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('h', 'Высший'), ('l', 'Низший'), ('m', 'Средний')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Чердаклинский', 'Чердаклинский район '), ('Базарносызганский', 'Базарносызганский район'), ('Цильнинский', 'Цильнинский район'), ('Тереньгульский', 'Тереньгульский район'), ('Карсунский', 'Карсунский район'), ('Павловский', 'Павловский район'), ('Старомайнский', 'Старомайнский район'), ('Вешкаймский', 'Вешкаймский район'), ('Барышский', 'Барышский район'), ('Николаевский', 'Николаевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Майнский', 'Майнский район'), ('Мелекесский', 'Мелекесский район'), ('Новоспасский', 'Новоспасский район'), ('Сурский', 'Сурский район'), ('Кузоватовский', 'Кузоватовский район')], max_length=25, verbose_name='Территория'),
        ),
    ]
