# Generated by Django 4.1 on 2022-09-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_doctor_territory_alter_patient_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Карсунский', 'Карсунский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('Николаевский', 'Николаевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Мелекесский', 'Мелекесский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Цильнинский', 'Цильнинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Майнский', 'Майнский район'), ('Радищевский', 'Радищевский район'), ('Старомайнский', 'Старомайнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Барышский', 'Барышский район'), ('Тереньгульский', 'Тереньгульский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('1-', 'O(I) Rh- '), ('3-', 'B(III) Rh- '), ('2+', 'A(II) Rh+ '), ('4+', 'AB(IV) Rh+'), ('4-', 'AB(IV) Rh-'), ('1+', 'O(I) Rh+ '), ('3+', 'B(III) Rh+ '), ('2-', 'A(II) Rh- ')], max_length=2, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_village',
            field=models.CharField(choices=[('1', 'Город'), ('2', 'Село')], max_length=1, verbose_name='Житель города/села'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья')], max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, choices=[('6', 'ООО «КАПИТАЛ МС» '), ('1', 'АО «Медицинская акционерная страховая компания» (АО «МАКС-М»)'), ('5', 'ООО «Страховая компания «Ингосстрах-М»'), ('3', 'ООО «Страховая медицинская компания РЕСО-МЕД» (Московский филиал)'), ('2', 'ООО «МСК «МЕДСТРАХ»»'), ('4', 'АО «Страховая компания «СОГАЗ-Мед»»')], max_length=1, verbose_name='Сраховая компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(blank=True, choices=[('h', 'Высший'), ('m', 'Средний'), ('l', 'Низший')], max_length=1, verbose_name='Соц. Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='territory',
            field=models.CharField(choices=[('Карсунский', 'Карсунский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('Николаевский', 'Николаевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Мелекесский', 'Мелекесский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Цильнинский', 'Цильнинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Майнский', 'Майнский район'), ('Радищевский', 'Радищевский район'), ('Старомайнский', 'Старомайнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Барышский', 'Барышский район'), ('Тереньгульский', 'Тереньгульский район')], max_length=25, verbose_name='Территория'),
        ),
        migrations.CreateModel(
            name='ReceptionNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting', models.DateTimeField(verbose_name='Время приема')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
            options={
                'verbose_name': 'Запись приема',
                'verbose_name_plural': 'Записи приема',
                'ordering': ['-date_meeting', '-date_updated'],
            },
        ),
    ]
