# Generated by Django 4.1.1 on 2022-10-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('терапевт ', 'терапевт'), ('специалист', 'специалист'), ('офтальмолог', 'офтальмолог'), ('стоматолог', 'стоматолог'), ('педиатор', 'педиатор'), ('акушер-гинеколог', 'акушер-гинеколог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Новоспасский', 'Новоспасский район'), ('Старомайнский', 'Старомайнский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Радищевский', 'Радищевский район'), ('Сурский', 'Сурский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Майнский', 'Майнский район'), ('Вешкаймский', 'Вешкаймский район'), ('', '----'), ('Барышский', 'Барышский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Мелекесский', 'Мелекесский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='gynecological_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Гинекологические  заболевания'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('3', 'Состоит в незарегистрированном браке'), ('5', 'Разведена'), ('4', 'Вдова'), ('2', 'Состоит в зарегистрированном браке'), ('', '----'), ('6', 'Разошлась'), ('1', 'Никогда не состояла в браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='somatic_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Соматические заболевания'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('30-40', 'Явка на 30-40 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', '----'), ('m', 'Мужской'), ('f', 'Женский')], default='f', max_length=1, verbose_name='Пол'),
        ),
    ]
