# Generated by Django 4.0.2 on 2022-10-08 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('специалист', 'специалист'), ('офтальмолог', 'офтальмолог'), ('педиатор', 'педиатор'), ('стоматолог', 'стоматолог'), ('терапевт ', 'терапевт'), ('акушер-гинеколог', 'акушер-гинеколог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Старомайнский', 'Старомайнский район'), ('Кузоватовский', 'Кузоватовский район'), ('Вешкаймский', 'Вешкаймский район'), ('Инзенский', 'Инзенский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Радищевский', 'Радищевский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Майнский', 'Майнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Карсунский', 'Карсунский район'), ('', '----'), ('Николаевский', 'Николаевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Мелекесский', 'Мелекесский район'), ('Сурский', 'Сурский район'), ('Павловский', 'Павловский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Барышский', 'Барышский район'), ('Цильнинский', 'Цильнинский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='gynecological_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Гинекологические  заболевания'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('6', 'Разошлась'), ('', '----'), ('1', 'Никогда не состояла в браке'), ('5', 'Разведена'), ('2', 'Состоит в зарегистрированном браке'), ('3', 'Состоит в незарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='somatic_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Соматические заболевания'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('18-20', 'Явка на 18-20 неделе'), ('11-14', 'Явка на 11-14 неделе'), ('1', 'Первая явка'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', '----'), ('m', 'Мужской'), ('f', 'Женский')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='PregnancyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Беременность по счету')),
                ('childbirth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата исхода беременности')),
                ('pregnancy_outcome', models.CharField(blank=True, choices=[('р', 'Роды'), ('с', 'Смерть'), ('а', 'Аборт')], max_length=10, null=True, verbose_name='Исход беременности')),
                ('if_childbirth', models.CharField(blank=True, choices=[('со', 'Самопроизводьным - с осложнениями'), ('сбо', 'Самопроизводьным - без осложнений'), ('окс', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды')),
                ('if_abortion', models.CharField(blank=True, choices=[('с', 'Самопроизвольный'), ('и', 'Искусственный')], max_length=10, null=True, verbose_name='Аборт')),
                ('death_time', models.DateTimeField(blank=True, null=True, verbose_name='Смерть')),
                ('disease', models.CharField(max_length=10, verbose_name='Причина смерти (шифр по МКБ-10)')),
                ('gestation_period_weeks', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Срок беременности (недели)')),
                ('number_of_fetuses', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Количество плодов')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_outcome', to='home.patient')),
            ],
        ),
    ]
