# Generated by Django 4.1.1 on 2022-10-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complicationrisk',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='home.obstetricrisk'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('специалист', 'специалист'), ('стоматолог', 'стоматолог'), ('офтальмолог', 'офтальмолог'), ('акушер-гинеколог', 'акушер-гинеколог'), ('педиатор', 'педиатор'), ('терапевт ', 'терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Старомайнский', 'Старомайнский район'), ('Павловский', 'Павловский район'), ('Барышский', 'Барышский район'), ('Сурский', 'Сурский район'), ('Базарносызганский', 'Базарносызганский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Ульяновский', 'Ульяновский район'), ('Радищевский', 'Радищевский район'), ('Новоспасский', 'Новоспасский район'), ('', '----'), ('Инзенский', 'Инзенский район'), ('Николаевский', 'Николаевский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('Майнский', 'Майнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Цильнинский', 'Цильнинский район'), ('Вешкаймский', 'Вешкаймский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('1', 'O(I)'), ('2', 'A(II)'), ('4', 'AB(IV)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('3', 'Состоит в незарегистрированном браке'), ('2', 'Состоит в зарегистрированном браке'), ('', '----'), ('6', 'Разошлась'), ('4', 'Вдова'), ('1', 'Никогда не состояла в браке'), ('5', 'Разведена')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('1', 'O(I)'), ('2', 'A(II)'), ('4', 'AB(IV)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('18-20', 'Явка на 18-20 неделе'), ('30-40', 'Явка на 30-40 неделе'), ('11-14', 'Явка на 11-14 неделе'), ('1', 'Первая явка')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Женский'), ('m', 'Мужской'), ('', '----')], default='f', max_length=1, verbose_name='Пол'),
        ),
    ]
