# Generated by Django 4.1 on 2022-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_comprehensiveriskassessment_trisomy_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takingmedications',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Наименование лекарственного препарата'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_13',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='ПЭ поздний (до 37 недель)'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_18',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='18 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_21',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='21 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='zrp',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='ЗРП'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Первая'), ('4', 'Индуцирована с помощью ВРТ'), ('2', 'Повторная'), ('3', 'Наступила спонтанно')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('2', 'Повторные'), ('1', 'Первые'), ('', '')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатор'), ('specialist', 'Специалист'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('therapist', 'Терапевт'), ('dentist', 'Стоматолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Майнский', 'Майнский район'), ('Новоспасский', 'Новоспасский район'), ('Ульяновский', 'Ульяновский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Инзенский', 'Инзенский район'), ('Павловский', 'Павловский район'), ('Сурский', 'Сурский район'), ('Вешкаймский', 'Вешкаймский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Радищевский', 'Радищевский район'), ('', '----'), ('Николаевский', 'Николаевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Старомайнский', 'Старомайнский район'), ('Чердаклинский', 'Чердаклинский район '), ('Цильнинский', 'Цильнинский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Мелекесский', 'Мелекесский район'), ('Барышский', 'Барышский район'), ('Кузоватовский', 'Кузоватовский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='doctorexaminationsdentist',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='doctorexaminationstherapist',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('', '----'), ('d', 'Наркотики'), ('a', 'Алкоголь'), ('s', 'Курение')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('1', 'Плотная'), ('3', 'Мягкая'), ('', ''), ('2', 'Размягченная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Пропускает кончик пальца'), ('1', 'Пропускает палец'), ('1', 'Сомкнут')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('попер', 'Попереченое'), ('кос', 'Косое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Патологических изменений нет'), ('3', 'Безболезненны '), ('4', 'Масталгия'), ('2', 'Пальпируется узловое образование')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Втянуты'), ('1', 'Сформированы правильно')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('2', 'По мужскому типу'), ('1', 'По женскому типу'), ('4', 'Нормально выражена'), ('', ''), ('5', 'Избыточно выражена'), ('3', 'Недостаточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('др', 'Другое'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Безболезненное'), ('1', 'Подвижное'), ('3', 'Болезненное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=150, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('3', 'Состоит в незарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('', '----'), ('5', 'Разведена'), ('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='med_org',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=150, null=True, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='another_risks',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Другие риски'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('1', 'Состояла'), ('0', 'Не состояла')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='growth_retardation_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск задержки роста плода'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('1', 'Положительный'), ('0', 'Отрицательный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='preeclampsia_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преэклампсии'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='premature_birth_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преждевременных родов'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('1', 'Скудные'), ('3', 'Обильные'), ('2', 'Умеренные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='thromboembolic_complications',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск тромбоэболических осложнений'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('swc', 'Самопроизвольным - без осложнений'), ('ocs', 'Оперативным - кесарево сечение'), ('sc', 'Самопроизвольным - с осложнениями')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('попер', 'Попереченое'), ('кос', 'Косое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('др', 'Другое'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='med_organization',
            field=models.CharField(blank=True, choices=[('', '----'), ('1', 'Больница 1'), ('2', 'Больница 2'), ('3', 'Больница 3')], max_length=10, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатор'), ('specialist', 'Специалист'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('therapist', 'Терапевт'), ('dentist', 'Стоматолог')], default='----', max_length=30, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('2', 'Многоводие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('2', 'Многоводие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
    ]
