# Generated by Django 4.0.2 on 2022-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_doctor_role_alter_doctor_territory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregnancyoutcome',
            options={'verbose_name': 'Исход беременности', 'verbose_name_plural': 'Исходы беременностей'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('терапевт ', 'терапевт'), ('специалист', 'специалист'), ('стоматолог', 'стоматолог'), ('офтальмолог', 'офтальмолог'), ('акушер-гинеколог', 'акушер-гинеколог'), ('педиатор', 'педиатор')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Павловский', 'Павловский район'), ('Барышский', 'Барышский район'), ('Новоспасский', 'Новоспасский район'), ('Тереньгульский', 'Тереньгульский район'), ('Базарносызганский', 'Базарносызганский район'), ('Мелекесский', 'Мелекесский район'), ('Инзенский', 'Инзенский район'), ('Радищевский', 'Радищевский район'), ('Чердаклинский', 'Чердаклинский район '), ('Новомалыклинский', 'Новомалыклинский район'), ('', '----'), ('Сенгилеевский', 'Сенгилеевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Ульяновский', 'Ульяновский район'), ('Старомайнский', 'Старомайнский район'), ('Цильнинский', 'Цильнинский район'), ('Сурский', 'Сурский район'), ('Карсунский', 'Карсунский район'), ('Вешкаймский', 'Вешкаймский район'), ('Кузоватовский', 'Кузоватовский район'), ('Николаевский', 'Николаевский район'), ('Майнский', 'Майнский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('2', 'Состоит в зарегистрированном браке'), ('6', 'Разошлась'), ('1', 'Никогда не состояла в браке'), ('3', 'Состоит в незарегистрированном браке'), ('', '----'), ('4', 'Вдова'), ('5', 'Разведена')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('30-40', 'Явка на 30-40 неделе'), ('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе'), ('18-20', 'Явка на 18-20 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('', '----'), ('f', 'Женский')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='disease',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Причина смерти (шифр по МКБ-10)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('и', 'Искусственный'), ('с', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('окс', 'Оперативным - кесарево сечение'), ('со', 'Самопроизводьным - с осложнениями'), ('сбо', 'Самопроизводьным - без осложнений')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('с', 'Смерть'), ('а', 'Аборт'), ('р', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
    ]
