# Generated by Django 4.1 on 2022-10-23 21:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_takingmedications_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_13',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий'), ('', '')], max_length=1, null=True, verbose_name='ПЭ поздний (до 37 недель)'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_18',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий'), ('', '')], max_length=1, null=True, verbose_name='18 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_21',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий'), ('', '')], max_length=1, null=True, verbose_name='21 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('2', 'Левая'), ('1', 'Правая'), ('', '')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='zrp',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('0', 'Низкий'), ('', '')], max_length=1, null=True, verbose_name='ЗРП'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Криоконсервированного'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('2', 'Повторная'), ('4', 'Индуцирована с помощью ВРТ'), ('', ''), ('1', 'Первая'), ('3', 'Наступила спонтанно')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('2', 'Многоплодность'), ('1', 'Одноплодность'), ('', '')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатор'), ('ophthalmologist', 'Офтальмолог'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог'), ('therapist', 'Терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Инзенский', 'Инзенский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Барышский', 'Барышский район'), ('Майнский', 'Майнский район'), ('Павловский', 'Павловский район'), ('Николаевский', 'Николаевский район'), ('Радищевский', 'Радищевский район'), ('', '----'), ('Старокулаткинский', 'Старокулаткинский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сурский', 'Сурский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Карсунский', 'Карсунский район'), ('Мелекесский', 'Мелекесский район'), ('Старомайнский', 'Старомайнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Цильнинский', 'Цильнинский район'), ('Новоспасский', 'Новоспасский район'), ('Ульяновский', 'Ульяновский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('d', 'Наркотики'), ('s', 'Курение'), ('', '----'), ('a', 'Алкоголь')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('2', 'Размягченная'), ('3', 'Мягкая'), ('1', 'Плотная'), ('', '')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Кпереди'), ('3', 'Расположена по центру'), ('1', 'Кзади')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('1', 'Сомкнут'), ('1', 'Пропускает палец'), ('', ''), ('1', 'Пропускает кончик пальца')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('попер', 'Попереченое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Без особенностей'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('1', 'Патологических изменений нет'), ('2', 'Пальпируется узловое образование'), ('3', 'Безболезненны '), ('', ''), ('4', 'Масталгия')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('1', 'Сформированы правильно'), ('2', 'Втянуты'), ('', '')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Без особенностей'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('5', 'Избыточно выражена'), ('2', 'По мужскому типу'), ('', ''), ('1', 'По женскому типу'), ('4', 'Нормально выражена'), ('3', 'Недостаточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('гол', 'Головка'), ('др', 'Другое'), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('3', 'Болезненное'), ('1', 'Подвижное'), ('2', 'Безболезненное'), ('', '')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('1', 'Экстренная'), ('0', 'Плановая'), ('', '')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('1', 'В отделение акушерского ухода'), ('0', 'В отделение патологии беременности'), ('', '')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)'), ('4', 'AB(IV)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('6', 'Разошлась'), ('1', 'Никогда не состояла в браке'), ('', '----'), ('2', 'Состоит в зарегистрированном браке'), ('5', 'Разведена'), ('3', 'Состоит в незарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)'), ('4', 'AB(IV)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('30-40', 'Явка на 30-40 неделе'), ('1', 'Первая явка'), ('18-20', 'Явка на 18-20 неделе'), ('11-14', 'Явка на 11-14 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', '----'), ('m', 'Мужской'), ('f', 'Женский')], default='f', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц'), ('', '----')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('0', 'Не состояла'), ('1', 'Состояла')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('3', 'Обильные'), ('1', 'Скудные'), ('2', 'Умеренные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('<1/2', 'Меньше 1/2 пачки'), ('1/2-1', 'От 1/2 до 1 пачки'), ('', '----'), ('1>', 'Больше 1 пачки')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('s', 'Самопроизвольный'), ('a', 'Искусственный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('swc', 'Самопроизвольным - без осложнений'), ('sc', 'Самопроизвольным - с осложнениями'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('a', 'Аборт'), ('d', 'Смерть'), ('b', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('попер', 'Попереченое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('гол', 'Головка'), ('др', 'Другое'), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(choices=[('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатор'), ('ophthalmologist', 'Офтальмолог'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог'), ('therapist', 'Терапевт')], default='----', max_length=30, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('1', 'Тазовое'), ('0', 'Головное'), ('', '')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
        migrations.CreateModel(
            name='PreviousPregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год')),
                ('pragnancy_has_come', models.CharField(blank=True, choices=[('2', 'Индуцироваа'), ('1', 'Самопроизовльно'), ('3', 'ВРТ'), ('', '')], max_length=10, null=True, verbose_name='Насупила')),
                ('outcome', models.CharField(blank=True, choices=[('3', 'Самопроизовльный выкидыш'), ('4', 'Искисственный аборт'), ('6', 'Пузырный занос'), ('', ''), ('1', 'Срочные/Преждевременные'), ('2', 'Кесарево сечение'), ('5', 'Неразвивающаяся беременность')], max_length=10, null=True, verbose_name='Исход беременности')),
                ('outcome_str', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация')),
                ('birth_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Число родившихся')),
                ('birth_str', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация')),
                ('complications', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Осложнения предыдущих беременносей и родов')),
                ('doctor_confirmation', models.BooleanField(default=False, null=True, verbose_name='Подтверждение врача')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_pregnancy', to='home.patient')),
            ],
        ),
    ]
