# Generated by Django 4.1.2 on 2022-10-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_comprehensiveriskassessment_trisomy_13_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('1', 'Нативного'), ('2', 'Криоконсервированного'), ('', '')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('4', 'Индуцирована с помощью ВРТ'), ('', ''), ('1', 'Первая'), ('2', 'Повторная'), ('3', 'Наступила спонтанно')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Первые'), ('2', 'Повторные')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('specialist', 'Специалист'), ('pediator', 'Педиатор')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Ульяновский', 'Ульяновский район'), ('Радищевский', 'Радищевский район'), ('Тереньгульский', 'Тереньгульский район'), ('Мелекесский', 'Мелекесский район'), ('Чердаклинский', 'Чердаклинский район '), ('', '----'), ('Кузоватовский', 'Кузоватовский район'), ('Старомайнский', 'Старомайнский район'), ('Новоспасский', 'Новоспасский район'), ('Павловский', 'Павловский район'), ('Вешкаймский', 'Вешкаймский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Сурский', 'Сурский район'), ('Карсунский', 'Карсунский район'), ('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Майнский', 'Майнский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('d', 'Наркотики'), ('a', 'Алкоголь'), ('s', 'Курение'), ('', '----')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('2', 'Размягченная'), ('1', 'Плотная'), ('3', 'Мягкая'), ('', '')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('3', 'Расположена по центру'), ('2', 'Кпереди'), ('1', 'Кзади'), ('', '')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('1', 'Пропускает палец'), ('1', 'Пропускает кончик пальца'), ('1', 'Сомкнут'), ('', '')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('попер', 'Попереченое'), ('кос', 'Косое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('1', 'Без особенностей'), ('2', 'Есть особенности'), ('', '')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Пальпируется узловое образование'), ('3', 'Безболезненны '), ('4', 'Масталгия'), ('1', 'Патологических изменений нет')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Сформированы правильно'), ('2', 'Втянуты')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('1', 'Без особенностей'), ('2', 'Есть особенности'), ('', '')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('1', 'По женскому типу'), ('4', 'Нормально выражена'), ('', ''), ('5', 'Избыточно выражена'), ('2', 'По мужскому типу'), ('3', 'Недостаточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('гол', 'Головка'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('5', 'Разведена'), ('', '----'), ('3', 'Состоит в незарегистрированном браке'), ('2', 'Состоит в зарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('6', 'Разошлась'), ('4', 'Вдова')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('', '----'), ('1-2m', '1-2 раза в месяц'), ('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('0', 'Отрицательный'), ('1', 'Положительный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('1', 'Болезненные'), ('0', 'Безболезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('3', 'Обильные'), ('2', 'Умеренные'), ('1', 'Скудные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('1/2-1', 'От 1/2 до 1 пачки'), ('', '----'), ('1>', 'Больше 1 пачки'), ('<1/2', 'Меньше 1/2 пачки')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('a', 'Искусственный'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('b', 'Роды'), ('a', 'Аборт'), ('d', 'Смерть')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='blood_pressure_diastolic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артериальное давление диастолическое (мм.рт.ст.)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('попер', 'Попереченое'), ('кос', 'Косое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='protein_in_urine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Белок в моче (мг)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='systolic_blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артериальное давление систолическое (мм.рт.ст.)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('гол', 'Головка'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('1', 'Срочные/Преждевременные'), ('6', 'Пузырный занос'), ('4', 'Искисственный аборт'), ('2', 'Кесарево сечение'), ('', ''), ('3', 'Самопроизовльный выкидыш'), ('5', 'Неразвивающаяся беременность')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Самопроизовльно'), ('2', 'Индуцироваа'), ('3', 'ВРТ')], max_length=10, null=True, verbose_name='Насупила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('specialist', 'Специалист'), ('pediator', 'Педиатор')], default='----', max_length=30, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('0', 'Норма'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('0', 'Норма'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
    ]
