# Generated by Django 4.1.2 on 2022-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_appointmentlist_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('1', 'Правая'), ('2', 'Левая'), ('', '')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Криоконсервированного'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('3', 'Наступила спонтанно'), ('', ''), ('2', 'Повторная'), ('4', 'Индуцирована с помощью ВРТ')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('2', 'Повторные'), ('1', 'Первые'), ('', '')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('obstetrician-gynecologist', 'Акушер-гинеколог'), ('specialist', 'Специалист'), ('', ''), ('ophthalmologist', 'Офтальмолог'), ('nurse', 'Медсестра'), ('therapist', 'Терапевт'), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('dentist', 'Стоматолог'), ('pediator', 'Педиатор')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Цильнинский', 'Цильнинский район'), ('Новоспасский', 'Новоспасский район'), ('Вешкаймский', 'Вешкаймский район'), ('Радищевский', 'Радищевский район'), ('Старомайнский', 'Старомайнский район'), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Павловский', 'Павловский район'), ('', ''), ('Базарносызганский', 'Базарносызганский район'), ('Майнский', 'Майнский район'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Сурский', 'Сурский район'), ('Инзенский', 'Инзенский район'), ('Старокулаткинский', 'Старокулаткинский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('s', 'Курение'), ('a', 'Алкоголь'), ('d', 'Наркотики'), ('', '')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', ''), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('', ''), ('3', 'Расположена по центру'), ('1', 'Кзади'), ('2', 'Кпереди')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Сомкнут'), ('2', 'Пропускает кончик пальца'), ('3', 'Пропускает палец')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('', ''), ('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Есть особенности'), ('1', 'Без особенностей')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('4', 'Масталгия'), ('2', 'Пальпируется узловое образование'), ('3', 'Безболезненны '), ('1', 'Патологических изменений нет'), ('', '')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Есть особенности'), ('1', 'Без особенностей')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('5', 'Избыточно выражена'), ('3', 'Недостаточно выражена'), ('4', 'Нормально выражена'), ('', ''), ('1', 'По женскому типу'), ('2', 'По мужскому типу')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('гол', 'Головка'), ('', ''), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('1', 'Подвижное'), ('3', 'Болезненное'), ('2', 'Безболезненное'), ('', '')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'В отделение акушерского ухода'), ('0', 'В отделение патологии беременности')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Группа 1'), ('3', 'Группа 3'), ('2', 'Группа 2'), ('', '')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('2', 'Среднее'), ('2', 'Высшее'), ('1', 'Начальное'), ('', '')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('1', 'O(I)'), ('', ''), ('3', 'B(III)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('', '')], max_length=1, null=True, verbose_name='Rh-фактор отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('3', 'Состоит в незарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('5', 'Разведена'), ('', '----'), ('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('1', 'O(I)'), ('', ''), ('3', 'B(III)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('', '')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', '1 уровень'), ('2', '2 уровень'), ('3', '3 уровень'), ('', '')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('18-20', 'Явка на 18-20 неделе'), ('', ''), ('11-14', 'Явка на 11-14 неделе'), ('1', 'Первая явка'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('', ''), ('1-2m', '1-2 раза в месяц'), ('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('1', 'Состояла'), ('0', 'Не состояла'), ('', '')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('1', 'Болезненные'), ('0', 'Безболезненные'), ('', '')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('1', 'Скудные'), ('2', 'Умеренные'), ('3', 'Обильные'), ('', '')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('1/2-1', 'От 1/2 до 1 пачки'), ('<1/2', 'Меньше 1/2 пачки'), ('1>', 'Больше 1 пачки'), ('', '')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('', ''), ('a', 'Искусственный'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('', ''), ('sc', 'Самопроизвольным - с осложнениями'), ('swc', 'Самопроизвольным - без осложнений'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('', ''), ('a', 'Аборт'), ('d', 'Смерть'), ('b', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', ''), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('', ''), ('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('гол', 'Головка'), ('', ''), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('6', 'Пузырный занос'), ('5', 'Неразвивающаяся беременность'), ('', ''), ('2', 'Кесарево сечение'), ('4', 'Искусственный аборт'), ('3', 'Самопроизовльный выкидыш'), ('1', 'Срочные/Преждевременные')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('', ''), ('3', 'ВРТ'), ('1', 'Самопроизовльно'), ('2', 'Индуцирована')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(choices=[('obstetrician-gynecologist', 'Акушер-гинеколог'), ('specialist', 'Специалист'), ('', ''), ('ophthalmologist', 'Офтальмолог'), ('nurse', 'Медсестра'), ('therapist', 'Терапевт'), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('dentist', 'Стоматолог'), ('pediator', 'Педиатор')], max_length=30, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус явки'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
    ]
