# Generated by Django 4.1.2 on 2022-12-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_file_remove_receptionnotes_visit_number_and_more'),
        ('home', '0034_alter_appointmentlist_service_and_more'),
    ]

    operations = [
    ]
