# Generated by Django 4.1.2 on 2022-12-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_merge_20221210_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('1', 'Лабораторная диагностика'), ('3', 'Консультация'), ('2', 'Инструментальная диагностика'), ('', '')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('1', 'Правая'), ('2', 'Левая'), ('', '')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('1', 'Нативного'), ('2', 'Криоконсервированного'), ('', '')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('4', 'Индуцирована с помощью ВРТ'), ('3', 'Наступила спонтанно'), ('2', 'Повторная'), ('', ''), ('1', 'Первая')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('2', 'Многоплодность'), ('1', 'Одноплодность'), ('', '')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('1', 'Первые'), ('2', 'Повторные'), ('', '')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('assistant', 'Лаборант'), ('ophthalmologist', 'Офтальмолог'), ('', ''), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра'), ('therapist', 'Терапевт'), ('pediator', 'Педиатр'), ('dentist', 'Стоматолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Карсунский', 'Карсунский район'), ('Радищевский', 'Радищевский район'), ('Цильнинский', 'Цильнинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Павловский', 'Павловский район'), ('Ульяновский', 'Ульяновский район'), ('Инзенский', 'Инзенский район'), ('Мелекесский', 'Мелекесский район'), ('Вешкаймский', 'Вешкаймский район'), ('Чердаклинский', 'Чердаклинский район '), ('', ''), ('Кузоватовский', 'Кузоватовский район'), ('Майнский', 'Майнский район'), ('Новоспасский', 'Новоспасский район'), ('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Тереньгульский', 'Тереньгульский район'), ('Старомайнский', 'Старомайнский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('d', 'Наркотики'), ('a', 'Алкоголь'), ('s', 'Курение'), ('', '')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('3', 'Мягкая'), ('1', 'Плотная'), ('', ''), ('2', 'Размягченная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('3', 'Расположена по центру'), ('1', 'Кзади'), ('2', 'Кпереди'), ('', '')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('1', 'Сомкнут'), ('3', 'Пропускает палец'), ('2', 'Пропускает кончик пальца'), ('', '')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('прод', 'Продольное'), ('попер', 'Попереченое'), ('', '')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('', ''), ('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('1', 'Без особенностей'), ('', '')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('1', 'Патологических изменений нет'), ('', ''), ('3', 'Безболезненны '), ('4', 'Масталгия'), ('2', 'Пальпируется узловое образование')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('1', 'Сформированы правильно'), ('2', 'Втянуты'), ('', '')], max_length=1, verbose_name='Осмотр и пальпация сосков'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('1', 'Без особенностей'), ('', '')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('4', 'Нормально выражена'), ('1', 'По женскому типу'), ('5', 'Избыточно выражена'), ('', ''), ('2', 'По мужскому типу'), ('3', 'Недостаточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('гол', 'Головка'), ('', '')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('1', 'Подвижное'), ('2', 'Безболезненное'), ('3', 'Болезненное'), ('', '')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Плановая'), ('1', 'Экстренная')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('1', 'В отделение акушерского ухода'), ('0', 'В отделение патологии беременности'), ('', '')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('3', 'Группа 3'), ('2', 'Группа 2'), ('1', 'Группа 1'), ('', '')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('', ''), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('2', 'Состоит в зарегистрированном браке'), ('3', 'Состоит в незарегистрированном браке'), ('', '----'), ('5', 'Разведена'), ('6', 'Разошлась'), ('1', 'Никогда не состояла в браке'), ('4', 'Вдова')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('', ''), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('', ''), ('3', '3 уровень'), ('1', '1 уровень'), ('2', '2 уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('1', 'Первая явка'), ('', ''), ('18-20', 'Явка на 18-20 неделе'), ('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1-2w', '1-2 раза в неделю'), ('1', 'Каждый день'), ('1-2m', '1-2 раза в месяц'), ('', '')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('0', 'Не состояла'), ('1', 'Состояла'), ('', '')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('3', 'Обильные'), ('1', 'Скудные'), ('2', 'Умеренные'), ('', '')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('', ''), ('swc', 'Самопроизвольным - без осложнений'), ('ocs', 'Оперативным - кесарево сечение'), ('sc', 'Самопроизвольным - с осложнениями')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('d', 'Смерть'), ('a', 'Аборт'), ('b', 'Роды'), ('', '')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('прод', 'Продольное'), ('попер', 'Попереченое'), ('', '')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('', ''), ('+', 'Ощущается'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('гол', 'Головка'), ('', '')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', ''), ('4', 'Искусственный аборт'), ('3', 'Самопроизовльный выкидыш'), ('5', 'Неразвивающаяся беременность'), ('2', 'Кесарево сечение'), ('1', 'Срочные/Преждевременные'), ('6', 'Пузырный занос')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='date_meeting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время приема'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='date_recording',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='service',
            field=models.CharField(blank=True, choices=[('antibody detection', 'Определение антител'), ('antibodies to pale treponema', 'Антитела к бледной трепонеме'), ('rubella virus', 'Вирус краснухи'), ('anti-rhesus bodies', 'Антирезусные тела'), ('blood analysis', 'Анализ крови'), ('blood chemistry', 'Биохимический анализ крови'), ('coagulogram', 'Коагулограмма'), ('oral glucose tolerance test, mmol/l', 'Пероральный глюкозотолерантный тест, ммоль/л'), ('level of thyroid stimulating hormone (TSH), μIU/l', 'Уровень тиретропного гормона (ТТГ), мкМЕ/л'), ('detection of group B streptococcus (S. agalactiae) in the discharge of the cervical canal or rectovaginal discharge', 'Определение стрептококка группы B (S. agalactiae) в отделяемом цервикального канала или ректовагинальном отделяемом'), ('bacterioscopic examination of smears', 'Бактериоскопическое исследование мазков'), ('cytological examination of a micropreparation of the cervix', 'Цитологическое исследование микропрепарата шейки матки'), ('General urine analysis', 'Общий анализ мочи'), ('urine culture for asymptomatic bacteriuria', 'Посев мочи на бессимптомную бактериурию'), ('ultrasound', 'УЗИ'), ('B01.047.001', 'B01.047.001 Прием (осмотр, консультация) врача-терапевта первичный'), ('B01.047.002', 'B01.047.002 Прием (осмотр, консультация) врача-терапевта повторный'), ('B01.047.005', 'B01.047.005 Прием (осмотр, консультация) врача-терапевта участкового первичный'), ('B01.047.006', 'B01.047.006 Прием (осмотр, консультация) врача-терапевта участкового повторный'), ('B01.065.001', 'B01.065.001 Прием (осмотр, консультация) врача-стоматолога-терапевта первичный'), ('B01.065.002', 'B01.065.002 Прием (осмотр, консультация) врача-стоматолога-терапевта повторный'), ('B01.065.007', 'B01.065.007 Прием (осмотр, консультация) врача-стоматолога первичный'), ('B01.065.008', 'B01.065.008 Прием (осмотр, консультация) врача-стоматолога повторный'), ('B01.029.001', 'B01.029.001 Прием (осмотр, консультация) врача-офтальмолога первичный'), ('B01.029.002', 'B01.029.002 Прием (осмотр, консультация) врача-офтальмолога повторный'), ('B01.028.001', 'B01.028.001 Прием (осмотр, консультация) врача-оториноларинголога первичный'), ('B01.028.002', 'B01.028.002 Прием (осмотр, консультация) врача-оториноларинголога повторный'), ('B01.001.001', 'B01.001.001 Прием (осмотр, консультация) врача-акушера-гинеколога первичный'), ('B01.001.002', 'B01.001.002 Прием (осмотр, консультация) врача-акушера-гинеколога повторный')], default='antibody detection', max_length=120, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('assistant', 'Лаборант'), ('ophthalmologist', 'Офтальмолог'), ('', ''), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра'), ('therapist', 'Терапевт'), ('pediator', 'Педиатр'), ('dentist', 'Стоматолог')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('5', 'Отправлен'), ('', ''), ('2', 'Неправильно введены данные'), ('1', 'Недостаточно данных'), ('3', 'Не подписан'), ('4', 'Готов к отправке')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('1', 'Маловодие'), ('2', 'Многоводие'), ('0', 'Норма'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('1', 'Маловодие'), ('2', 'Многоводие'), ('0', 'Норма'), ('', '')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
    ]
