# Generated by Django 4.1 on 2022-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_appointmentlist_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('3', 'Консультация'), ('1', 'Лабораторная диагностика'), ('2', 'Инструментальная диагностика')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('2', 'Левая'), ('1', 'Правая')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('2', 'Криоконсервированного'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('2', 'Повторная'), ('1', 'Первая'), ('3', 'Наступила спонтанно'), ('4', 'Индуцирована с помощью ВРТ')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('1', 'Первые'), ('2', 'Повторные')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('assistant', 'Лаборант'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт'), ('nurse', 'Медсестра'), ('ophthalmologist', 'Офтальмолог'), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Николаевский', 'Николаевский район'), ('Новоспасский', 'Новоспасский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Кузоватовский', 'Кузоватовский район'), ('Вешкаймский', 'Вешкаймский район'), ('Сурский', 'Сурский район'), ('Старомайнский', 'Старомайнский район'), ('Майнский', 'Майнский район'), ('Карсунский', 'Карсунский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Мелекесский', 'Мелекесский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('a', 'Алкоголь'), ('s', 'Курение'), ('d', 'Наркотики')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('2', 'Размягченная'), ('3', 'Мягкая'), ('1', 'Плотная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('2', 'Пропускает кончик пальца'), ('1', 'Сомкнут'), ('3', 'Пропускает палец')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('3', 'Безболезненны '), ('1', 'Патологических изменений нет'), ('4', 'Масталгия'), ('2', 'Пальпируется узловое образование')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('2', 'По мужскому типу'), ('4', 'Нормально выражена'), ('3', 'Недостаточно выражена'), ('5', 'Избыточно выражена'), ('1', 'По женскому типу')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('гол', 'Головка'), ('тк', 'Тазовый конец'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('2', 'Безболезненное'), ('1', 'Подвижное'), ('3', 'Болезненное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('1', 'В отделение акушерского ухода'), ('0', 'В отделение патологии беременности')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Группа 1'), ('3', 'Группа 3'), ('2', 'Группа 2')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('2', 'Среднее'), ('1', 'Начальное'), ('2', 'Высшее')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке'), ('4', 'Вдова'), ('3', 'Состоит в незарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('', '----'), ('5', 'Разведена')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Радищевский', 'Радищевский район'), ('Инзенский', 'Инзенский район'), ('Ульяновский', 'Ульяновский район'), ('Николаевский', 'Николаевский район'), ('Новоспасский', 'Новоспасский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Чердаклинский', 'Чердаклинский район '), ('Павловский', 'Павловский район'), ('Тереньгульский', 'Тереньгульский район'), ('Кузоватовский', 'Кузоватовский район'), ('Вешкаймский', 'Вешкаймский район'), ('Сурский', 'Сурский район'), ('Старомайнский', 'Старомайнский район'), ('Майнский', 'Майнский район'), ('Карсунский', 'Карсунский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Мелекесский', 'Мелекесский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'Первый уровень'), ('3', 'Третий уровень'), ('2', 'Второй уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('18-20', 'Явка на 18-20 неделе'), ('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('0', 'Отрицательный'), ('1', 'Положительный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('1', 'Болезненные'), ('0', 'Безболезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('3', 'Обильные'), ('1', 'Скудные'), ('2', 'Умеренные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('a', 'Искусственный'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('a', 'Аборт'), ('d', 'Смерть'), ('b', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('гол', 'Головка'), ('тк', 'Тазовый конец'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('5', 'Неразвивающаяся беременность'), ('2', 'Кесарево сечение'), ('1', 'Срочные/Преждевременные'), ('3', 'Самопроизовльный выкидыш'), ('6', 'Пузырный занос'), ('4', 'Искусственный аборт')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('1', 'Самопроизовльно'), ('2', 'Индуцирована'), ('3', 'ВРТ')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('assistant', 'Лаборант'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт'), ('nurse', 'Медсестра'), ('ophthalmologist', 'Офтальмолог'), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('2', 'Неправильно введены данные'), ('5', 'Отправлен'), ('1', 'Недостаточно данных'), ('4', 'Готов к отправке'), ('3', 'Не подписан')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('1', 'Тазовое'), ('0', 'Головное')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
