# Generated by Django 4.1.2 on 2022-12-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_appointmentlist_service_and_more'),
        ('home', '0041_doctor_access_and_more'),
    ]

    operations = [
    ]
