# Generated by Django 4.1 on 2022-12-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_appointmentlist_service_and_more'),
        ('home', '0039_doctor_access_medicalcard_territory_and_more'),
        ('home', '0041_alter_appointmentlist_service_and_more'),
        ('home', '0041_doctor_access_and_more'),
    ]

    operations = [
    ]
