# Generated by Django 4.1.2 on 2022-12-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_merge_20221215_2003'),
        ('home', '0042_merge_20221215_2017'),
    ]

    operations = [
    ]
