# Generated by Django 4.1 on 2022-12-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_merge_20221215_2003'),
        ('home', '0043_alter_appointmentlist_service_and_more'),
    ]

    operations = [
    ]
