# Generated by Django 4.1.2 on 2022-12-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_merge_20221216_0256'),
        ('home', '0045_notifications_created_alter_appointmentlist_service_and_more'),
    ]

    operations = [
    ]
