# Generated by Django 4.1 on 2022-12-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_merge_20221222_1845'),
        ('home', '0046_merge_20221222_2256'),
    ]

    operations = [
    ]
