# Generated by Django 4.1 on 2022-12-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_samd_model_remove_samd_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samd',
            name='was_send',
            field=models.BooleanField(default=False, verbose_name='Отправлен'),
        ),
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('3', 'Консультация'), ('', '-----'), ('1', 'Лабораторная диагностика'), ('2', 'Инструментальная диагностика')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Правая'), ('2', 'Левая')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Криоконсервированного'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('2', 'Повторная'), ('1', 'Первая'), ('3', 'Наступила спонтанно'), ('', '-----'), ('4', 'Индуцирована с помощью ВРТ')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('1', 'Одноплодность'), ('2', 'Многоплодность'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('2', 'Повторные'), ('', '-----'), ('1', 'Первые')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('', ''), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('dentist', 'Стоматолог'), ('specialist', 'Специалист'), ('therapist', 'Терапевт'), ('pediator', 'Педиатр'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Новомалыклинский', 'Новомалыклинский район'), ('Барышский', 'Барышский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('Ульяновский', 'Ульяновский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('', '-----'), ('Мелекесский', 'Мелекесский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('Цильнинский', 'Цильнинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Инзенский', 'Инзенский район'), ('Тереньгульский', 'Тереньгульский район'), ('Николаевский', 'Николаевский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Радищевский', 'Радищевский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('', '-----'), ('d', 'Наркотики'), ('s', 'Курение'), ('a', 'Алкоголь')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Плотная'), ('2', 'Размягченная'), ('3', 'Мягкая')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Пропускает кончик пальца'), ('1', 'Сомкнут'), ('3', 'Пропускает палец')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('', '-----'), ('кос', 'Косое'), ('попер', 'Попереченое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('3', 'Безболезненны '), ('', '-----'), ('4', 'Масталгия'), ('1', 'Патологических изменений нет'), ('2', 'Пальпируется узловое образование')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('5', 'Избыточно выражена'), ('4', 'Нормально выражена'), ('1', 'По женскому типу'), ('2', 'По мужскому типу'), ('', '-----'), ('3', 'Недостаточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('', '-----'), ('3', 'Болезненное'), ('2', 'Безболезненное'), ('1', 'Подвижное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Экстренная'), ('0', 'Плановая')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('', '-----'), ('3', 'Группа 3'), ('1', 'Группа 1'), ('2', 'Группа 2')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Высшее'), ('2', 'Среднее'), ('1', 'Начальное')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('', '-----'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('', '-----'), ('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке'), ('4', 'Вдова'), ('1', 'Никогда не состояла в браке'), ('5', 'Разведена'), ('3', 'Состоит в незарегистрированном браке'), ('', '----')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('3', 'B(III)'), ('', '-----'), ('1', 'O(I)'), ('4', 'AB(IV)'), ('2', 'A(II)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('', '-----'), ('-', '-'), ('+', '+')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Новомалыклинский', 'Новомалыклинский район'), ('Барышский', 'Барышский район'), ('Базарносызганский', 'Базарносызганский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('Ульяновский', 'Ульяновский район'), ('Карсунский', 'Карсунский район'), ('Кузоватовский', 'Кузоватовский район'), ('', '-----'), ('Мелекесский', 'Мелекесский район'), ('Новоспасский', 'Новоспасский район'), ('Майнский', 'Майнский район'), ('Цильнинский', 'Цильнинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Инзенский', 'Инзенский район'), ('Тереньгульский', 'Тереньгульский район'), ('Николаевский', 'Николаевский район'), ('Старомайнский', 'Старомайнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Радищевский', 'Радищевский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'Первый уровень'), ('', '-----'), ('2', 'Второй уровень'), ('3', 'Третий уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('', '-----')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1-2w', '1-2 раза в неделю'), ('1', 'Каждый день'), ('1-2m', '1-2 раза в месяц')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'Не состояла'), ('1', 'Состояла')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'Отрицательный'), ('1', 'Положительный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Скудные'), ('2', 'Умеренные'), ('3', 'Обильные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('1/2-1', 'От 1/2 до 1 пачки'), ('', '-----'), ('<1/2', 'Меньше 1/2 пачки'), ('1>', 'Больше 1 пачки')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('', '-----'), ('a', 'Искусственный'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('', '-----'), ('swc', 'Самопроизвольным - без осложнений'), ('sc', 'Самопроизвольным - с осложнениями'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('', '-----'), ('d', 'Смерть'), ('a', 'Аборт'), ('b', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('прод', 'Продольное'), ('', '-----'), ('кос', 'Косое'), ('попер', 'Попереченое')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка'), ('др', 'Другое')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('6', 'Пузырный занос'), ('2', 'Кесарево сечение'), ('3', 'Самопроизовльный выкидыш'), ('', '-----'), ('4', 'Искусственный аборт'), ('5', 'Неразвивающаяся беременность'), ('1', 'Срочные/Преждевременные')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('', '-----'), ('3', 'ВРТ'), ('2', 'Индуцирована'), ('1', 'Самопроизовльно')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ophthalmologist', 'Офтальмолог'), ('', ''), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('dentist', 'Стоматолог'), ('specialist', 'Специалист'), ('therapist', 'Терапевт'), ('pediator', 'Педиатр'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('4', 'Готов к отправке'), ('2', 'Неправильно введены данные'), ('5', 'Отправлен'), ('', '-----'), ('1', 'Недостаточно данных'), ('3', 'Не подписан')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'Норма'), ('2', 'Многоводие'), ('1', 'Маловодие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
    ]
