# Generated by Django 4.1 on 2022-12-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_responsemessages_alter_appointmentlist_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('2', 'Инструментальная диагностика'), ('3', 'Консультация'), ('1', 'Лабораторная диагностика'), ('', '-----')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('1', 'Правая'), ('2', 'Левая'), ('', '-----')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('1', 'Нативного'), ('', '-----'), ('2', 'Криоконсервированного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('3', 'Наступила спонтанно'), ('4', 'Индуцирована с помощью ВРТ'), ('2', 'Повторная'), ('1', 'Первая'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('1', 'Одноплодность'), ('', '-----'), ('2', 'Многоплодность')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Повторные'), ('1', 'Первые')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('nurse', 'Медсестра'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатр'), ('', ''), ('assistant', 'Лаборант'), ('therapist', 'Терапевт'), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Радищевский', 'Радищевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новоспасский', 'Новоспасский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Вешкаймский', 'Вешкаймский район'), ('', '-----'), ('Кузоватовский', 'Кузоватовский район'), ('Сурский', 'Сурский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Старомайнский', 'Старомайнский район'), ('Ульяновский', 'Ульяновский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Барышский', 'Барышский район'), ('Карсунский', 'Карсунский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('s', 'Курение'), ('', '-----'), ('a', 'Алкоголь'), ('d', 'Наркотики')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('3', 'Расположена по центру'), ('2', 'Кпереди'), ('', '-----'), ('1', 'Кзади')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('3', 'Пропускает палец'), ('2', 'Пропускает кончик пальца'), ('1', 'Сомкнут'), ('', '-----')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('кос', 'Косое'), ('', '-----'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('-', 'Не ощущается'), ('', '-----')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Без особенностей'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('1', 'Патологических изменений нет'), ('3', 'Безболезненны '), ('', '-----'), ('4', 'Масталгия'), ('2', 'Пальпируется узловое образование')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('1', 'Сформированы правильно'), ('2', 'Втянуты'), ('', '-----')], max_length=1, verbose_name='Осмотр и пальпация сосков'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Без особенностей'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('5', 'Избыточно выражена'), ('3', 'Недостаточно выражена'), ('', '-----'), ('1', 'По женскому типу'), ('2', 'По мужскому типу'), ('4', 'Нормально выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('2', 'Безболезненное'), ('1', 'Подвижное'), ('', '-----'), ('3', 'Болезненное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'В отделение патологии беременности'), ('1', 'В отделение акушерского ухода')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Группа 1'), ('2', 'Группа 2'), ('3', 'Группа 3'), ('', '-----')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Начальное'), ('2', 'Среднее'), ('', '-----'), ('2', 'Высшее')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('', '-----'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('6', 'Разошлась'), ('3', 'Состоит в незарегистрированном браке'), ('', '----'), ('2', 'Состоит в зарегистрированном браке'), ('5', 'Разведена'), ('4', 'Вдова'), ('1', 'Никогда не состояла в браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('2', 'A(II)'), ('1', 'O(I)'), ('', '-----'), ('4', 'AB(IV)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Николаевский', 'Николаевский район'), ('Радищевский', 'Радищевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новоспасский', 'Новоспасский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Майнский', 'Майнский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Вешкаймский', 'Вешкаймский район'), ('', '-----'), ('Кузоватовский', 'Кузоватовский район'), ('Сурский', 'Сурский район'), ('Цильнинский', 'Цильнинский район'), ('Инзенский', 'Инзенский район'), ('Старомайнский', 'Старомайнский район'), ('Ульяновский', 'Ульяновский район'), ('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Барышский', 'Барышский район'), ('Карсунский', 'Карсунский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'Первый уровень'), ('2', 'Второй уровень'), ('', '-----'), ('3', 'Третий уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе'), ('1', 'Первая явка'), ('18-20', 'Явка на 18-20 неделе'), ('', '-----')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц'), ('', '-----')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('1', 'Состояла'), ('', '-----'), ('0', 'Не состояла')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('1', 'Положительный'), ('', '-----'), ('0', 'Отрицательный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('0', 'Безболезненные'), ('', '-----'), ('1', 'Болезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('2', 'Умеренные'), ('1', 'Скудные'), ('', '-----'), ('3', 'Обильные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('s', 'Самопроизвольный'), ('', '-----'), ('a', 'Искусственный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('sc', 'Самопроизвольным - с осложнениями'), ('', '-----'), ('swc', 'Самопроизвольным - без осложнений'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('d', 'Смерть'), ('', '-----'), ('b', 'Роды'), ('a', 'Аборт')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('приж', 'Прижата'), ('под', 'Подвижна'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('кос', 'Косое'), ('', '-----'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('-', 'Не ощущается'), ('', '-----')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('3', 'Самопроизовльный выкидыш'), ('6', 'Пузырный занос'), ('4', 'Искусственный аборт'), ('1', 'Срочные/Преждевременные'), ('5', 'Неразвивающаяся беременность'), ('', '-----'), ('2', 'Кесарево сечение')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('3', 'ВРТ'), ('1', 'Самопроизовльно'), ('', '-----'), ('2', 'Индуцирована')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ophthalmologist', 'Офтальмолог'), ('nurse', 'Медсестра'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('pediator', 'Педиатр'), ('', ''), ('assistant', 'Лаборант'), ('therapist', 'Терапевт'), ('receptionist', 'Регистратор'), ('specialist', 'Специалист'), ('dentist', 'Стоматолог')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('5', 'Отправлен'), ('1', 'Недостаточно данных'), ('4', 'Готов к отправке'), ('3', 'Не подписан'), ('2', 'Неправильно введены данные'), ('', '-----')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('2', 'Выявление госпитализации (получение пациентом медицинской помощи в условиях стационара (дневного стационара))'), ('1', 'Выявление осмотра (консультации) пациента'), ('', '-----')], max_length=10, verbose_name='Тип СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('', '-----'), ('2', 'Многоводие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('', '-----'), ('2', 'Многоводие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('1', 'Тазовое'), ('', '-----'), ('0', 'Головное')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
