# Generated by Django 4.1 on 2023-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_comprehensiveriskassessment_preeclampcy_34_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего визита'),
        ),
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('3', 'Консультация'), ('1', 'Лабораторная диагностика'), ('', '-----'), ('2', 'Инструментальная диагностика')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('2', 'Криоконсервированного'), ('', '-----'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('2', 'Индуцирована с помощью ВРТ'), ('', '-----'), ('1', 'Наступила спонтанно')], max_length=1, verbose_name='Начало беременности'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('1', 'Одноплодность'), ('2', 'Многоплодность'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('1', 'Первые'), ('2', 'Повторные'), ('', '-----')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('specialist', 'Специалист'), ('', ''), ('assistant', 'Лаборант'), ('nurse', 'Медсестра'), ('dentist', 'Стоматолог'), ('receptionist', 'Регистратор'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Ульяновский', 'Ульяновский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новоспасский', 'Новоспасский район'), ('Вешкаймский', 'Вешкаймский район'), ('Кузоватовский', 'Кузоватовский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Мелекесский', 'Мелекесский район'), ('Старомайнский', 'Старомайнский район'), ('Павловский', 'Павловский район'), ('Майнский', 'Майнский район'), ('Сурский', 'Сурский район'), ('Тереньгульский', 'Тереньгульский район'), ('Цильнинский', 'Цильнинский район'), ('', '-----'), ('Карсунский', 'Карсунский район'), ('Радищевский', 'Радищевский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('под', 'Подвижна'), ('приж', 'Прижата')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('1', 'Плотная'), ('3', 'Мягкая'), ('', '-----'), ('2', 'Размягченная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('1', 'Кзади'), ('', '-----'), ('3', 'Расположена по центру'), ('2', 'Кпереди')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('3', 'Пропускает палец'), ('2', 'Пропускает кончик пальца'), ('', '-----'), ('1', 'Сомкнут')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('кос', 'Косое'), ('', '-----'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('1', 'Без особенностей'), ('', '-----')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('2', 'Пальпируется узловое образование'), ('3', 'Безболезненны '), ('', '-----'), ('1', 'Патологических изменений нет'), ('4', 'Масталгия')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('2', 'Втянуты'), ('1', 'Сформированы правильно'), ('', '-----')], max_length=1, verbose_name='Осмотр и пальпация сосков'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('1', 'Без особенностей'), ('', '-----')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('1', 'По женскому типу'), ('4', 'Нормально выражена'), ('', '-----'), ('3', 'Недостаточно выражена'), ('2', 'По мужскому типу'), ('5', 'Избыточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('гол', 'Головка'), ('', '-----'), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('2', 'Безболезненное'), ('1', 'Подвижное'), ('3', 'Болезненное'), ('', '-----')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'Плановая'), ('1', 'Экстренная')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('', '-----'), ('0', 'В отделение патологии беременности'), ('1', 'В отделение акушерского ухода')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('2', 'Среднее'), ('2', 'Высшее'), ('1', 'Начальное'), ('', '-----')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('', '-----')], max_length=1, null=True, verbose_name='Rh-фактор отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке'), ('', '----'), ('3', 'Состоит в незарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('5', 'Разведена')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('4', 'AB(IV)'), ('2', 'A(II)'), ('1', 'O(I)'), ('3', 'B(III)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('', '-----')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Барышский', 'Барышский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Ульяновский', 'Ульяновский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Николаевский', 'Николаевский район'), ('Базарносызганский', 'Базарносызганский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Новоспасский', 'Новоспасский район'), ('Вешкаймский', 'Вешкаймский район'), ('Кузоватовский', 'Кузоватовский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Мелекесский', 'Мелекесский район'), ('Старомайнский', 'Старомайнский район'), ('Павловский', 'Павловский район'), ('Майнский', 'Майнский район'), ('Сурский', 'Сурский район'), ('Тереньгульский', 'Тереньгульский район'), ('Цильнинский', 'Цильнинский район'), ('', '-----'), ('Карсунский', 'Карсунский район'), ('Радищевский', 'Радищевский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'Первый уровень'), ('3', 'Третий уровень'), ('', '-----'), ('2', 'Второй уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('1', 'Первая явка'), ('', '-----'), ('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе'), ('18-20', 'Явка на 18-20 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('', '-----'), ('1-2m', '1-2 раза в месяц'), ('1-2w', '1-2 раза в неделю')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('0', 'Отрицательный'), ('1', 'Положительный'), ('', '-----')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('1', 'Болезненные'), ('', '-----'), ('0', 'Безболезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('2', 'Умеренные'), ('3', 'Обильные'), ('1', 'Скудные'), ('', '-----')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('<1/2', 'Меньше 1/2 пачки'), ('1/2-1', 'От 1/2 до 1 пачки'), ('', '-----'), ('1>', 'Больше 1 пачки')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('s', 'Самопроизвольный'), ('', '-----'), ('a', 'Искусственный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('ocs', 'Оперативным - кесарево сечение'), ('sc', 'Самопроизвольным - с осложнениями'), ('', '-----'), ('swc', 'Самопроизвольным - без осложнений')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('b', 'Роды'), ('a', 'Аборт'), ('d', 'Смерть'), ('', '-----')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('под', 'Подвижна'), ('приж', 'Прижата')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('кос', 'Косое'), ('', '-----'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('гол', 'Головка'), ('', '-----'), ('тк', 'Тазовый конец')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('1', 'Срочные/Преждевременные'), ('6', 'Пузырный занос'), ('', '-----'), ('2', 'Кесарево сечение'), ('3', 'Самопроизовльный выкидыш'), ('4', 'Искусственный аборт'), ('5', 'Неразвивающаяся беременность')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('3', 'ВРТ'), ('', '-----'), ('2', 'Индуцирована'), ('1', 'Самопроизовльно')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('specialist', 'Специалист'), ('', ''), ('assistant', 'Лаборант'), ('nurse', 'Медсестра'), ('dentist', 'Стоматолог'), ('receptionist', 'Регистратор'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('3', 'Не подписан'), ('5', 'Отправлен'), ('4', 'Готов к отправке'), ('2', 'Неправильно введены данные'), ('', '-----'), ('1', 'Недостаточно данных')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('2', 'Выявление факта постановки на учет по беременности'), ('7', ''), ('1', 'Выявление осмотра (консультации) пациента'), ('6', 'Выявление факта завершения беременности'), ('', '-----'), ('8', 'Выявление извещения о критическом акушерском состоянии'), ('9', 'Выявление заключения по результатам расчета индивидуального риска беременной'), ('5', 'Выявление госпитализации (получение пациентом медицинской помощи в условиях стационара (дневного стационара))'), ('3', 'Выявление диагностических исследований'), ('4', '')], max_length=10, verbose_name='Тип СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('', '-----'), ('2', 'Многоводие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('0', 'Норма'), ('1', 'Маловодие'), ('', '-----'), ('2', 'Многоводие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('1', 'Тазовое'), ('', '-----'), ('0', 'Головное')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
