# Generated by Django 4.1 on 2023-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_appointmentlist_next_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentpregnancyinfo',
            name='pregnancy_start',
            field=models.CharField(blank=True, choices=[('1', 'Наступила спонтанно'), ('2', 'Индуцирована с помощью ВРТ'), ('', '-----')], max_length=1, verbose_name='Начало беременности'),
        ),
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('3', 'Консультация'), ('1', 'Лабораторная диагностика'), ('2', 'Инструментальная диагностика'), ('', '-----')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('1', 'Правая'), ('2', 'Левая'), ('', '-----')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('1', 'Нативного'), ('2', 'Криоконсервированного'), ('', '-----')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('2', 'Повторная'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('2', 'Многоплодность'), ('1', 'Одноплодность'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='upcoming_births',
            field=models.CharField(blank=True, choices=[('2', 'Повторные'), ('1', 'Первые'), ('', '-----')], max_length=1, verbose_name='Предстоящие роды'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('', ''), ('specialist', 'Специалист'), ('assistant', 'Лаборант'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт'), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('receptionist', 'Регистратор'), ('nurse', 'Медсестра')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Инзенский', 'Инзенский район'), ('', '-----'), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старомайнский', 'Старомайнский район'), ('Майнский', 'Майнский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Карсунский', 'Карсунский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Радищевский', 'Радищевский район'), ('Мелекесский', 'Мелекесский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('под', 'Подвижна'), ('приж', 'Прижата'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('2', 'Размягченная'), ('3', 'Мягкая'), ('1', 'Плотная'), ('', '-----')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('1', 'Кзади'), ('2', 'Кпереди'), ('3', 'Расположена по центру'), ('', '-----')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('1', 'Сомкнут'), ('3', 'Пропускает палец'), ('2', 'Пропускает кончик пальца'), ('', '-----')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('попер', 'Попереченое'), ('прод', 'Продольное'), ('', '-----')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('+', 'Ощущается'), ('', '-----')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('3', 'Безболезненны '), ('2', 'Пальпируется узловое образование'), ('4', 'Масталгия'), ('1', 'Патологических изменений нет'), ('', '-----')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='nipples',
            field=models.CharField(blank=True, choices=[('1', 'Сформированы правильно'), ('2', 'Втянуты'), ('', '-----')], max_length=1, verbose_name='Осмотр и пальпация сосков'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('5', 'Избыточно выражена'), ('1', 'По женскому типу'), ('3', 'Недостаточно выражена'), ('2', 'По мужскому типу'), ('4', 'Нормально выражена'), ('', '-----')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('др', 'Другое'), ('гол', 'Головка'), ('', '-----')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('3', 'Болезненное'), ('1', 'Подвижное'), ('2', 'Безболезненное'), ('', '-----')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('0', 'Плановая'), ('1', 'Экстренная'), ('', '-----')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('1', 'В отделение акушерского ухода'), ('0', 'В отделение патологии беременности'), ('', '-----')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('3', 'Группа 3'), ('1', 'Группа 1'), ('2', 'Группа 2'), ('', '-----')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('2', 'Высшее'), ('1', 'Начальное'), ('2', 'Среднее'), ('', '-----')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('3', 'B(III)'), ('2', 'A(II)'), ('4', 'AB(IV)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+'), ('', '-----')], max_length=1, null=True, verbose_name='Rh-фактор отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('', '----'), ('5', 'Разведена'), ('2', 'Состоит в зарегистрированном браке'), ('1', 'Никогда не состояла в браке'), ('3', 'Состоит в незарегистрированном браке'), ('6', 'Разошлась')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('3', 'B(III)'), ('2', 'A(II)'), ('4', 'AB(IV)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+'), ('', '-----')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Тереньгульский', 'Тереньгульский район'), ('Павловский', 'Павловский район'), ('Инзенский', 'Инзенский район'), ('', '-----'), ('Николаевский', 'Николаевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старомайнский', 'Старомайнский район'), ('Майнский', 'Майнский район'), ('Ульяновский', 'Ульяновский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Барышский', 'Барышский район'), ('Вешкаймский', 'Вешкаймский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Чердаклинский', 'Чердаклинский район '), ('Старокулаткинский', 'Старокулаткинский район'), ('Сурский', 'Сурский район'), ('Новоспасский', 'Новоспасский район'), ('Карсунский', 'Карсунский район'), ('Цильнинский', 'Цильнинский район'), ('Базарносызганский', 'Базарносызганский район'), ('Радищевский', 'Радищевский район'), ('Мелекесский', 'Мелекесский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('3', 'Третий уровень'), ('1', 'Первый уровень'), ('2', 'Второй уровень'), ('', '-----')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('1', 'Первая явка'), ('30-40', 'Явка на 30-40 неделе'), ('11-14', 'Явка на 11-14 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('', '-----')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('1-2m', '1-2 раза в месяц'), ('', '-----')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('1', 'Положительный'), ('0', 'Отрицательный'), ('', '-----')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('0', 'Безболезненные'), ('1', 'Болезненные'), ('', '-----')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('3', 'Обильные'), ('2', 'Умеренные'), ('1', 'Скудные'), ('', '-----')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('1/2-1', 'От 1/2 до 1 пачки'), ('<1/2', 'Меньше 1/2 пачки'), ('1>', 'Больше 1 пачки'), ('', '-----')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('s', 'Самопроизвольный'), ('a', 'Искусственный'), ('', '-----')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('sc', 'Самопроизвольным - с осложнениями'), ('swc', 'Самопроизвольным - без осложнений'), ('ocs', 'Оперативным - кесарево сечение'), ('', '-----')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('a', 'Аборт'), ('b', 'Роды'), ('d', 'Смерть'), ('', '-----')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('под', 'Подвижна'), ('приж', 'Прижата'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('попер', 'Попереченое'), ('прод', 'Продольное'), ('', '-----')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('+', 'Ощущается'), ('', '-----')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('тк', 'Тазовый конец'), ('др', 'Другое'), ('гол', 'Головка'), ('', '-----')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('2', 'Кесарево сечение'), ('1', 'Срочные/Преждевременные'), ('3', 'Самопроизовльный выкидыш'), ('6', 'Пузырный занос'), ('5', 'Неразвивающаяся беременность'), ('4', 'Искусственный аборт'), ('', '-----')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('2', 'Индуцирована'), ('1', 'Самопроизовльно'), ('', '-----'), ('3', 'ВРТ')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ophthalmologist', 'Офтальмолог'), ('', ''), ('specialist', 'Специалист'), ('assistant', 'Лаборант'), ('pediator', 'Педиатр'), ('therapist', 'Терапевт'), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('receptionist', 'Регистратор'), ('nurse', 'Медсестра')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('4', 'Готов к отправке'), ('2', 'Неправильно введены данные'), ('5', 'Отправлен'), ('3', 'Не подписан'), ('1', 'Недостаточно данных'), ('', '-----')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('9', 'Выявление заключения по результатам расчета индивидуального риска беременной'), ('8', 'Выявление извещения о критическом акушерском состоянии'), ('1', 'Выявление осмотра (консультации) пациента'), ('5', 'Выявление госпитализации (получение пациентом медицинской помощи в условиях стационара (дневного стационара))'), ('3', 'Выявление диагностических исследований'), ('', '-----'), ('6', 'Выявление факта завершения беременности'), ('7', ''), ('4', ''), ('2', 'Выявление факта постановки на учет по беременности')], max_length=10, verbose_name='Тип СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('0', 'Норма'), ('', '-----')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('0', 'Норма'), ('', '-----')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('0', 'Головное'), ('1', 'Тазовое'), ('', '-----')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
