# Generated by Django 4.1 on 2023-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_currentpregnancyinfo_upcoming_births_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('', '-----'), ('f', 'Женский')], max_length=10, null=True, verbose_name='Пол ребенка'),
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='child_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес ребенка (г.)'),
        ),
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('3', 'Консультация'), ('1', 'Лабораторная диагностика'), ('', '-----'), ('2', 'Инструментальная диагностика')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='preeclampcy_34',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='ПЭ ранней (до 34 недель)'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='preeclampcy_37',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='ПЭ поздний (до 37 недель)'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='premature_birth',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Преждевременные роды'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_13',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='13 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_18',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='18 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='trisomy_21',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='21 трисомии'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('2', 'Левая'), ('', '-----'), ('1', 'Правая')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='zrp',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Задержка развития плода'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Криоконсервированного'), ('1', 'Нативного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('2', 'Повторная'), ('', '-----')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('3', 'Кесарево сечение'), ('2', 'Индуцирована с помощью ВРТ'), ('', '-----'), ('1', 'Наступила спонтанно')], max_length=1, verbose_name='Завершение беременности'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('', ''), ('dentist', 'Стоматолог'), ('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатр'), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра'), ('specialist', 'Специалист'), ('therapist', 'Терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Новоспасский', 'Новоспасский район'), ('', '-----'), ('Старомайнский', 'Старомайнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Карсунский', 'Карсунский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Вешкаймский', 'Вешкаймский район'), ('Барышский', 'Барышский район'), ('Радищевский', 'Радищевский район'), ('Майнский', 'Майнский район'), ('Базарносызганский', 'Базарносызганский район'), ('Ульяновский', 'Ульяновский район'), ('Кузоватовский', 'Кузоватовский район'), ('Павловский', 'Павловский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('s', 'Курение'), ('', '-----'), ('a', 'Алкоголь'), ('d', 'Наркотики')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('под', 'Подвижна'), ('приж', 'Прижата'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('1', 'Плотная'), ('3', 'Мягкая'), ('', '-----'), ('2', 'Размягченная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('1', 'Кзади'), ('2', 'Кпереди'), ('', '-----'), ('3', 'Расположена по центру')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('', '-----'), ('попер', 'Попереченое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('1', 'Без особенностей'), ('', '-----'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('2', 'Пальпируется узловое образование'), ('', '-----'), ('3', 'Безболезненны '), ('1', 'Патологических изменений нет'), ('4', 'Масталгия')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('1', 'Без особенностей'), ('', '-----'), ('2', 'Есть особенности')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('3', 'Недостаточно выражена'), ('', '-----'), ('1', 'По женскому типу'), ('4', 'Нормально выражена'), ('2', 'По мужскому типу'), ('5', 'Избыточно выражена')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('3', 'Болезненное'), ('1', 'Подвижное'), ('', '-----'), ('2', 'Безболезненное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('0', 'Плановая'), ('1', 'Экстренная'), ('', '-----')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('0', 'В отделение патологии беременности'), ('', '-----'), ('1', 'В отделение акушерского ухода')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', 'Группа 1'), ('3', 'Группа 3'), ('', '-----'), ('2', 'Группа 2')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('2', 'Среднее'), ('2', 'Высшее'), ('', '-----'), ('1', 'Начальное')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('', '-----'), ('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('', '-----'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('1', 'Никогда не состояла в браке'), ('2', 'Состоит в зарегистрированном браке'), ('6', 'Разошлась'), ('5', 'Разведена'), ('', '----'), ('3', 'Состоит в незарегистрированном браке')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('', '-----'), ('4', 'AB(IV)'), ('1', 'O(I)'), ('2', 'A(II)'), ('3', 'B(III)')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('', '-----'), ('-', '-')], max_length=1, null=True, verbose_name='Rh-фактор'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Новоспасский', 'Новоспасский район'), ('', '-----'), ('Старомайнский', 'Старомайнский район'), ('Тереньгульский', 'Тереньгульский район'), ('Инзенский', 'Инзенский район'), ('Чердаклинский', 'Чердаклинский район '), ('Мелекесский', 'Мелекесский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Цильнинский', 'Цильнинский район'), ('Карсунский', 'Карсунский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Вешкаймский', 'Вешкаймский район'), ('Барышский', 'Барышский район'), ('Радищевский', 'Радищевский район'), ('Майнский', 'Майнский район'), ('Базарносызганский', 'Базарносызганский район'), ('Ульяновский', 'Ульяновский район'), ('Кузоватовский', 'Кузоватовский район'), ('Павловский', 'Павловский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('3', 'Третий уровень'), ('1', 'Первый уровень'), ('', '-----'), ('2', 'Второй уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Первая явка'), ('11-14', 'Явка на 11-14 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('30-40', 'Явка на 30-40 неделе')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Каждый день'), ('1-2w', '1-2 раза в неделю'), ('', '-----'), ('1-2m', '1-2 раза в месяц')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='another_risks',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Другие риски'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='dispensary_accounting',
            field=models.CharField(blank=True, choices=[('0', 'Не состояла'), ('', '-----'), ('1', 'Состояла')], max_length=1, null=True, verbose_name='Диспансерский учет'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='growth_retardation_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск задержки роста плода'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('0', 'Отрицательный'), ('1', 'Положительный'), ('', '-----')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('0', 'Безболезненные'), ('', '-----'), ('1', 'Болезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='preeclampsia_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преэклампсии'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='premature_birth_risk',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск преждевременных родов'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('', '-----'), ('3', 'Обильные'), ('1', 'Скудные'), ('2', 'Умеренные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='smoking',
            field=models.CharField(blank=True, choices=[('<1/2', 'Меньше 1/2 пачки'), ('', '-----'), ('1>', 'Больше 1 пачки'), ('1/2-1', 'От 1/2 до 1 пачки')], max_length=10, null=True, verbose_name='Курение (в день)'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='thromboembolic_complications',
            field=models.CharField(blank=True, choices=[('1', 'Высокий'), ('', '-----'), ('0', 'Низкий')], max_length=1, null=True, verbose_name='Риск тромбоэболических осложнений'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('a', 'Искусственный'), ('', '-----'), ('s', 'Самопроизвольный')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('swc', 'Самопроизвольным - без осложнений'), ('sc', 'Самопроизвольным - с осложнениями'), ('', '-----'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('d', 'Смерть'), ('b', 'Роды'), ('', '-----'), ('a', 'Аборт')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('под', 'Подвижна'), ('приж', 'Прижата'), ('', '-----')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('кос', 'Косое'), ('', '-----'), ('попер', 'Попереченое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('-', 'Не ощущается'), ('', '-----'), ('+', 'Ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('2', 'Кесарево сечение'), ('', '-----'), ('5', 'Неразвивающаяся беременность'), ('3', 'Самопроизовльный выкидыш'), ('1', 'Срочные/Преждевременные'), ('4', 'Искусственный аборт'), ('6', 'Пузырный занос')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('2', 'Индуцирована'), ('1', 'Самопроизовльно'), ('', '-----'), ('3', 'ВРТ')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', ''), ('dentist', 'Стоматолог'), ('ophthalmologist', 'Офтальмолог'), ('pediator', 'Педиатр'), ('assistant', 'Лаборант'), ('receptionist', 'Регистратор'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('nurse', 'Медсестра'), ('specialist', 'Специалист'), ('therapist', 'Терапевт')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('5', 'Отправлен'), ('', '-----'), ('2', 'Неправильно введены данные'), ('4', 'Готов к отправке'), ('3', 'Не подписан'), ('1', 'Недостаточно данных')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2', 'Выявление факта постановки на учет по беременности'), ('1', 'Выявление осмотра (консультации) пациента'), ('5', 'Выявление госпитализации (получение пациентом медицинской помощи в условиях стационара (дневного стационара))'), ('3', 'Выявление диагностических исследований'), ('6', 'Выявление факта завершения беременности'), ('9', 'Выявление заключения по результатам расчета индивидуального риска беременной'), ('4', ''), ('8', 'Выявление извещения о критическом акушерском состоянии'), ('7', '')], max_length=10, verbose_name='Тип СМС'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('', '-----'), ('0', 'Норма')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('1', 'Маловодие'), ('', '-----'), ('0', 'Норма')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('1', 'Тазовое'), ('0', 'Головное'), ('', '-----')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
