# Generated by Django 4.1 on 2023-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_pregnancyoutcome_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='at_inght',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='На ночь'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='breakfast_2h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Через 2ч. после еды'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='breakfast_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='breakfast_bu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='breakfast_i_p',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Утро'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='dinner_2h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Через 2ч. после еды'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='dinner_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='dinner_bu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='dinner_i_p',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='supper_2h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Через 2ч. после еды'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='supper_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='supper_bu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='selfmonitoringrecords',
            name='supper_i_p',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вечер'),
        ),
        migrations.AlterField(
            model_name='appointmentlist',
            name='service',
            field=models.CharField(blank=True, choices=[('1', 'Лабораторная диагностика'), ('2', 'Инструментальная диагностика'), ('', '-----'), ('3', 'Консультация')], max_length=10, null=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='comprehensiveriskassessment',
            name='uterine_pulse_index',
            field=models.CharField(blank=True, choices=[('1', 'Правая'), ('', '-----'), ('2', 'Левая')], max_length=1, null=True, verbose_name='ПИ маточных артерий'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='embryo_transfer',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Нативного'), ('2', 'Криоконсервированного')], max_length=1, verbose_name='Перенос эмбрионов'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('1', 'Первая'), ('', '-----'), ('2', 'Повторная')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_1',
            field=models.CharField(blank=True, choices=[('2', 'Многоплодность'), ('', '-----'), ('1', 'Одноплодность')], max_length=1, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='currentpregnancyinfo',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('2', 'Индуцирована с помощью ВРТ'), ('3', 'Кесарево сечение'), ('', '-----'), ('1', 'Наступила спонтанно')], max_length=1, verbose_name='Завершение беременности'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('', ''), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('assistant', 'Лаборант'), ('ophthalmologist', 'Офтальмолог'), ('specialist', 'Специалист'), ('nurse', 'Медсестра'), ('pediator', 'Педиатр'), ('receptionist', 'Регистратор'), ('therapist', 'Терапевт')], default='----', max_length=30, verbose_name='Должность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='territory',
            field=models.CharField(choices=[('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Мелекесский', 'Мелекесский район'), ('Барышский', 'Барышский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Радищевский', 'Радищевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старомайнский', 'Старомайнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('', '-----'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Чердаклинский', 'Чердаклинский район '), ('Цильнинский', 'Цильнинский район'), ('Майнский', 'Майнский район'), ('Ульяновский', 'Ульяновский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Инзенский', 'Инзенский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='bad_habits',
            field=models.CharField(blank=True, choices=[('d', 'Наркотики'), ('', '-----'), ('a', 'Алкоголь'), ('s', 'Курение')], max_length=10, null=True, verbose_name='Вредные привычки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix',
            field=models.CharField(blank=True, choices=[('3', 'Мягкая'), ('2', 'Размягченная'), ('', '-----'), ('1', 'Плотная')], max_length=10, null=True, verbose_name='Шейка матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='cervix_deviations',
            field=models.CharField(blank=True, choices=[('2', 'Кпереди'), ('1', 'Кзади'), ('', '-----'), ('3', 'Расположена по центру')], max_length=10, null=True, verbose_name='Отклонения шейки матки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='external_pharynx',
            field=models.CharField(blank=True, choices=[('1', 'Сомкнут'), ('', '-----'), ('3', 'Пропускает палец'), ('2', 'Пропускает кончик пальца')], max_length=1, null=True, verbose_name='Наружний зев'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('', '-----'), ('кос', 'Косое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('', '-----'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='left_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('', '-----'), ('1', 'Без особенностей')], max_length=1, null=True, verbose_name='Придатки слева'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='mammary',
            field=models.CharField(blank=True, choices=[('3', 'Безболезненны '), ('2', 'Пальпируется узловое образование'), ('1', 'Патологических изменений нет'), ('', '-----'), ('4', 'Масталгия')], max_length=1, verbose_name='Осмотр и пальпация молочных желез'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='right_appendages',
            field=models.CharField(blank=True, choices=[('2', 'Есть особенности'), ('', '-----'), ('1', 'Без особенностей')], max_length=1, null=True, verbose_name='Придатки справа'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='subcutaneous_fat_severity',
            field=models.CharField(blank=True, choices=[('4', 'Нормально выражена'), ('2', 'По мужскому типу'), ('3', 'Недостаточно выражена'), ('5', 'Избыточно выражена'), ('', '-----'), ('1', 'По женскому типу')], max_length=1, verbose_name='Распределение и выраженность подкожной жировой клетчатки'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз (после 34 недель)'),
        ),
        migrations.AlterField(
            model_name='firstexamination',
            name='uterus_body',
            field=models.CharField(blank=True, choices=[('', '-----'), ('1', 'Подвижное'), ('2', 'Безболезненное'), ('3', 'Болезненное')], max_length=1, null=True, verbose_name='Тело матки. Характеристика'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='hosp_type',
            field=models.CharField(blank=True, choices=[('1', 'Экстренная'), ('', '-----'), ('0', 'Плановая')], max_length=1, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinformation',
            name='where',
            field=models.CharField(blank=True, choices=[('1', 'В отделение акушерского ухода'), ('', '-----'), ('0', 'В отделение патологии беременности')], max_length=1, verbose_name='Медицинская организация'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='disability',
            field=models.CharField(blank=True, choices=[('2', 'Группа 2'), ('', '-----'), ('1', 'Группа 1'), ('3', 'Группа 3')], max_length=200, null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Начальное'), ('', '-----'), ('2', 'Среднее'), ('2', 'Высшее')], max_length=5, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='father_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови отца ребенка'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('4', 'Вдова'), ('1', 'Никогда не состояла в браке'), ('6', 'Разошлась'), ('2', 'Состоит в зарегистрированном браке'), ('', '----'), ('3', 'Состоит в незарегистрированном браке'), ('5', 'Разведена')], default='', max_length=1, null=True, verbose_name='Брачное состояние'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mother_blood_group',
            field=models.CharField(blank=True, choices=[('1', 'O(I)'), ('3', 'B(III)'), ('4', 'AB(IV)'), ('2', 'A(II)'), ('', '-----')], max_length=1, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='territory',
            field=models.CharField(choices=[('Сурский', 'Сурский район'), ('Николаевский', 'Николаевский район'), ('Мелекесский', 'Мелекесский район'), ('Барышский', 'Барышский район'), ('Старокулаткинский', 'Старокулаткинский район'), ('Радищевский', 'Радищевский район'), ('Кузоватовский', 'Кузоватовский район'), ('Старомайнский', 'Старомайнский район'), ('Сенгилеевский', 'Сенгилеевский район'), ('Вешкаймский', 'Вешкаймский район'), ('Павловский', 'Павловский район'), ('', '-----'), ('Карсунский', 'Карсунский район'), ('Тереньгульский', 'Тереньгульский район'), ('Чердаклинский', 'Чердаклинский район '), ('Цильнинский', 'Цильнинский район'), ('Майнский', 'Майнский район'), ('Ульяновский', 'Ульяновский район'), ('Новоспасский', 'Новоспасский район'), ('Базарносызганский', 'Базарносызганский район'), ('Новомалыклинский', 'Новомалыклинский район'), ('Инзенский', 'Инзенский район')], default='Ульяновский', max_length=25, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='modelivery',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'Первый уровень'), ('2', 'Второй уровень'), ('', '-----'), ('3', 'Третий уровень')], max_length=10, null=True, verbose_name='МО родоразрешения'),
        ),
        migrations.AlterField(
            model_name='obstetricrisk',
            name='visit',
            field=models.CharField(blank=True, choices=[('11-14', 'Явка на 11-14 неделе'), ('30-40', 'Явка на 30-40 неделе'), ('18-20', 'Явка на 18-20 неделе'), ('', '-----'), ('1', 'Первая явка')], max_length=5, null=True, verbose_name='Срок явки'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1-2w', '1-2 раза в неделю'), ('', '-----'), ('1', 'Каждый день'), ('1-2m', '1-2 раза в месяц')], max_length=10, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('1', 'Положительный'), ('', '-----'), ('0', 'Отрицательный')], max_length=1, null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='painfulness',
            field=models.CharField(blank=True, choices=[('1', 'Болезненные'), ('', '-----'), ('0', 'Безболезненные')], max_length=10, null=True, verbose_name='Болезненность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='profusion',
            field=models.CharField(blank=True, choices=[('1', 'Скудные'), ('2', 'Умеренные'), ('', '-----'), ('3', 'Обильные')], max_length=10, null=True, verbose_name='Обильность'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='regularity',
            field=models.CharField(blank=True, choices=[('0', 'Нерегулярные'), ('', '-----'), ('1', 'Регулярные')], max_length=10, null=True, verbose_name='Регулярность'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('f', 'Женский'), ('', '-----'), ('m', 'Мужской')], max_length=10, null=True, verbose_name='Пол ребенка'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_abortion',
            field=models.CharField(blank=True, choices=[('s', 'Самопроизвольный'), ('a', 'Искусственный'), ('', '-----')], max_length=10, null=True, verbose_name='Аборт'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='if_childbirth',
            field=models.CharField(blank=True, choices=[('sc', 'Самопроизвольным - с осложнениями'), ('swc', 'Самопроизвольным - без осложнений'), ('', '-----'), ('ocs', 'Оперативным - кесарево сечение')], max_length=10, null=True, verbose_name='Роды'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='pregnancy_outcome',
            field=models.CharField(blank=True, choices=[('d', 'Смерть'), ('a', 'Аборт'), ('', '-----'), ('b', 'Роды')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='adjacent_part',
            field=models.CharField(blank=True, choices=[('', '-----'), ('приж', 'Прижата'), ('под', 'Подвижна')], max_length=10, null=True, verbose_name='Предлежащая часть'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetal_position',
            field=models.CharField(blank=True, choices=[('попер', 'Попереченое'), ('', '-----'), ('кос', 'Косое'), ('прод', 'Продольное')], max_length=10, null=True, verbose_name='Положение плода'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='fetus_stirring',
            field=models.CharField(blank=True, choices=[('+', 'Ощущается'), ('', '-----'), ('-', 'Не ощущается')], max_length=10, null=True, verbose_name='Шевеление плода: (>16 недель)'),
        ),
        migrations.AlterField(
            model_name='pregnantwomanmonitoring',
            name='to_pelvis_entrance',
            field=models.CharField(blank=True, choices=[('др', 'Другое'), ('тк', 'Тазовый конец'), ('', '-----'), ('гол', 'Головка')], max_length=10, null=True, verbose_name='Над входом в малый таз'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='outcome',
            field=models.CharField(blank=True, choices=[('3', 'Самопроизовльный выкидыш'), ('6', 'Пузырный занос'), ('5', 'Неразвивающаяся беременность'), ('2', 'Кесарево сечение'), ('4', 'Искусственный аборт'), ('1', 'Срочные/Преждевременные'), ('', '-----')], max_length=10, null=True, verbose_name='Исход беременности'),
        ),
        migrations.AlterField(
            model_name='previouspregnancy',
            name='pragnancy_has_come',
            field=models.CharField(blank=True, choices=[('2', 'Индуцирована'), ('3', 'ВРТ'), ('', '-----'), ('1', 'Самопроизовльно')], max_length=10, null=True, verbose_name='Наступила'),
        ),
        migrations.AlterField(
            model_name='receptionnotes',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', ''), ('dentist', 'Стоматолог'), ('obstetrician-gynecologist', 'Акушер-гинеколог'), ('assistant', 'Лаборант'), ('ophthalmologist', 'Офтальмолог'), ('specialist', 'Специалист'), ('nurse', 'Медсестра'), ('pediator', 'Педиатр'), ('receptionist', 'Регистратор'), ('therapist', 'Терапевт')], max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('1', 'Недостаточно данных'), ('5', 'Отправлен'), ('2', 'Неправильно введены данные'), ('4', 'Готов к отправке'), ('', '-----'), ('3', 'Не подписан')], max_length=300, verbose_name='Статус версии СМС'),
        ),
        migrations.AlterField(
            model_name='samd',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('3', 'Выявление диагностических исследований'), ('7', ''), ('2', 'Выявление факта постановки на учет по беременности'), ('', '-----'), ('6', 'Выявление факта завершения беременности'), ('8', 'Выявление извещения о критическом акушерском состоянии'), ('1', 'Выявление осмотра (консультации) пациента'), ('9', 'Выявление заключения по результатам расчета индивидуального риска беременной'), ('4', ''), ('5', 'Выявление госпитализации (получение пациентом медицинской помощи в условиях стационара (дневного стационара))')], max_length=10, verbose_name='Тип СМС'),
        ),
        migrations.AlterField(
            model_name='selfmonitoringrecords',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='selfmonitoringrecords',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_19_21',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('', '-----'), ('0', 'Норма'), ('1', 'Маловодие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='amniotic_fluid',
            field=models.CharField(blank=True, choices=[('2', 'Многоводие'), ('', '-----'), ('0', 'Норма'), ('1', 'Маловодие')], max_length=1, null=True, verbose_name='Околоплодные воды'),
        ),
        migrations.AlterField(
            model_name='ultrasoundexamination_30_34',
            name='presentation',
            field=models.CharField(blank=True, choices=[('0', 'Головное'), ('', '-----'), ('1', 'Тазовое')], max_length=1, null=True, verbose_name='Предлежание'),
        ),
    ]
